### ISSUE TITLE
use keyword arguments

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/ruby-vips#102]
We have ruby 2.0 as our minimum, so we could use keyword arguments instead of an optional trailing hash. This would be a bit faster and neater.

See https://github.com/jcupitt/ruby-vips/issues/101

**Comment by ioquatix** [comment]
Yay, I think this is a great idea. Do you want to have a go at it? Can I give you any help or suggestions?

**Comment by jcupitt** [comment]
I don't have much time right now. A PR would be fantastic!

**Comment by ioquatix** [comment]
So, FYI:

```ruby
def foo_args(*args)
  # Contains all args, including keyword args
end

def foo_args_options(*args, **options)
  # args contains positional
  # options contains keywords
  foo_args(*args) # pass all args
end

def required_keyword(*args, keyword:, **options)
end

def optional_keyword(*args, keyword:nil, **options)
end
```

**Comment by jcupitt** [comment]
There's a new ruby-vips in developmenmt here:

**Comment by jcupitt** [comment]
I tried (I think) the simplest change to try this. I changed:

https://github.com/jcupitt/ruby-vips/blob/ffi-experiment/lib/vips/image.rb#L175

```ruby
        def method_missing name, *args
            Vips::Operation::call name.to_s, [self] + args 
        end
```

to be:

```ruby
        def method_missing name, *args, **options
            Vips::Operation::call name.to_s, [self] + args + [options]
        end
```

Which (I think?) should be equivalent, but this makes 8 tests fail with "to_hash undefined". For example:

```
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> image = Vips::Image.black(16, 16)
=> #<Image 16x16 uchar, 1 bands, b-w>
irb(main):003:0> image + image
Vips::Error: VipsOperation: class "to_hash" not found

	from /home/john/.gem/gems/ruby-vips-2.0.0/lib/vips/operation.rb:65:in `initialize'
	from /home/john/.gem/gems/ruby-vips-2.0.0/lib/vips/operation.rb:225:in `new'
	from /home/john/.gem/gems/ruby-vips-2.0.0/lib/vips/operation.rb:225:in `call'
	from /home/john/.gem/gems/ruby-vips-2.0.0/lib/vips/image.rb:176:in `method_missing'
	from /home/john/.gem/gems/ruby-vips-2.0.0/lib/vips/image.rb:660:in `+'
	from (irb):3
	from /usr/bin/irb:11:in `<main>'
```

Why is `+` trying to call `to_hash` on one argument?

**Comment by ioquatix** [comment]
I don't know what `Vips::Operation::call` does, but here is some feedback:

- Using method_missing is very slow.
- Building a new array like that isn't going to be fast because you are generating temporaries which are immediately discarded. Better to write `[self, *args, options]`
- You are passing `[self] + args + [options]` as an array as the last argument, but do you mean to write `**([self] + args + [options])`

**Comment by jcupitt** [comment]
I think it has to use `method_missing` to do dynamic binding -- `image.banana` needs to look inside libvips for an operation called `banana` and run that. 

Good point on using * to explode args, I'll try that.

`Operation::call` looks like this:

```ruby
    def self.call name, supplied, option_string = ""
````

Where `supplied` is an array of arguments supplied to the operator, with an optional final hash of named args. 

https://github.com/jcupitt/ruby-vips/blob/ffi-experiment/lib/vips/operation.rb#L221

I'll see if I can make a tiny example of using `method_missing` and keyword args.

**Comment by jcupitt** [comment]
Here's a tiny program to show the behaviour:

```ruby
class A
    def self.call name, args, string_options = ""
        puts "A::call"
        puts "    name = #{name}"
        puts "    args = #{args}"
        puts "    string_options = #{string_options}"
    end
end

class B

    def method_missing name, *args, **options
        puts "B::method_missing"
        puts "    name = #{name}"
        puts "    args = #{args}"
        puts "    options = #{options}"

        A::call name.to_s, [self, *args, options]
    end

    def + other
        add other 
    end

end

x = B.new

y = x + x 
```

I see:

```
B::method_missing
    name = to_hash
    args = []
    options = {}
A::call
    name = to_hash
    args = [#<B:0x0055b3be094288>, {}]
    string_options = 
B::method_missing
    name = add
    args = [#<B:0x0055b3be094288>]
    options = {}
A::call
    name = add
    args = [#<B:0x0055b3be094288>, #<B:0x0055b3be094288>, {}]
    string_options = 
```

I'm puzzled it's searching for `to_hash`. I found this blog post:

https://makandracards.com/makandra/36013-heads-up-ruby-implicitly-converts-a-hash-to-keyword-arguments

So it seems Ruby will call `to_hash` on any final argument in case it can be converted into a set of keyword args. I added:

```ruby
   def to_hash
       nil
   end
```

To `Image` and that seems to have fixed it. How strange!

**Comment by jcupitt** [comment]
OK, all done! Thanks for suggesting this, @ioquatix

**Comment by ioquatix** [comment]
I think if you ensure that you don't respond to `#to_hash` that would be a better solution.

e.g.

```ruby
class Image
    def respond_to?(name)
        return false if name == :to_hash
    end
end
```

**Comment by ioquatix** [comment]
Again, this might be a symptom of using `method_missing`.

**Comment by jcupitt** [comment]
OK, changed the `to_hash` to:

```ruby
    def respond_to? name, include_all = false
        return false if name == :to_hash
        super
    end
```

And it seems to work. Thanks!

**Comment by ioquatix** [comment]
Just FYI, `method_missing` and `respond_to?` should work in tandem. So, you shouldn't generally respond to things using `method_missing` without also ensuring that `respond_to?` returns true for that method name.

**Comment by jcupitt** [comment]
That makes sense, thanks!

I implemented `self.respond_to?` as well, though that was just a guess.
