### ISSUE TITLE
Best way to get high resolution PDFs (SVGs, Vectors)

### ISSUE THREAD

**Issue by ioquatix** [jcupitt/ruby-vips#103]
I want to load a PDF and resize it using VIPS.

The PDF loads and has a small size

```
[2] pry(main)> i = Vips::Image.new_from_file("pages/newsletters/_newsletters/2017-Term1.pdf")
=> #<Vips::Image:0x7fcdd2046eb8 ptr=0x7fcdd2236020>
[3] pry(main)> i.size
=> [595, 841]
```

Yet, it's a scalable document, it could be any size I want. How do I load it so that it has a larger size?

Sorry, if this question is not very clear. Perhaps there are alternatives, please help me to understand if you think I'm not doing the right thing here.

**Comment by ioquatix** [comment]
Okay, I figured it out myself after reading https://github.com/jcupitt/libvips/issues/523

```
[1] pry(main)> i = Vips::Image.new_from_file("pages/newsletters/_newsletters/2017-Term1.pdf", scale: 10)
=> #<Vips::Image:0x7fddf7a7d0a0 ptr=0x7fddf7fb6020>
[2] pry(main)> i.size
=> [5952, 8418]
```

**Comment by ioquatix** [comment]
So, I guess I have one more question. If I know the size I want is width x height, how do I load the PDF so that it satisfies this constraint?

I can just hard code scale for now.. but it seems wasteful. IT would be nice to say, load this pdf so its minimum dimensions are above some set unit.

**Comment by jcupitt** [comment]
You open twice: the first time to get the "natural" size of the PDF, the second time with a scale calculated to produce the number of pixels you need. SVG and JPEG/WebP (with shrink-on-load) work the same way. 

You can see the code thumbnail uses here:

https://github.com/jcupitt/libvips/blob/master/libvips/resample/thumbnail.c#L240

libvips works hard to make the initial open quick, so there shouldn't be a performance issue.

**Comment by ioquatix** [comment]
So, opening doesn't load the whole thing into memory?

**Comment by jcupitt** [comment]
All the vips loaders are split into two: something to peek the header and pull out the metadata, and something to load (or render) the pixels. The pixel one is only used when pixels are really needed.

There are a few formats where this doesn't work, like CSV, where you have to parse the entire file to get the height, but that's rare. 

libMagick has `PingImage()` which is supposed to just read the image data, but unfortunately it's too unreliable and vips has to used `ReadImage()` to get the header, so libMagick-supported formats are slow too.

**Comment by ioquatix** [comment]
I'm surprised to hear that libvips uses libMagick.

Thanks for the detailed explanation.

**Comment by jcupitt** [comment]
libMagick is a fallback in case none of the native loaders recognise the file. It gets used for things like DCM, BMP or NEF. 

Projects like sharp generally disable it because of security concerns.
