### ISSUE TITLE
Vips::Image.page_height missing?

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/ruby-vips#105]
Have upgraded to Vips 8.5.2 and now I can get all pages in a multi-page TIFF loaded, thank you!

However, it looks as though the new `page-height` attribute hasn't been mapped?

**Comment by jcupitt** [comment]
Strange, it's working for me. I see:

```
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.new_from_file "multi-channel-z-series.ome.tif", n: -1
=> #<Vips::Image:0x55b7d7d222f8 ptr=0x55b7d83fa020>
irb(main):003:0> x.get_value "page-height"
=> 167
irb(main):004:0> x.width
=> 439
irb(main):005:0> x.height
=> 2505
```

That's with the sample OME-TIFF image in `libvips/test/images`:

https://github.com/jcupitt/libvips/tree/master/test/images

**Comment by harukizaemon** [comment]
Ahh. My misunderstanding! I assumed it was available as an instance attribute LOL. My bad. Thanks for clearing that up!

**Comment by jcupitt** [comment]
Ah OK. Yes, it's too easy for a stray image with some metadata called "each" (for example) to cause huge confusion inside Ruby. Core metadata appears as attributes, but you must use `get_value` for extra stuff.

**Comment by harukizaemon** [comment]
All good now, thank you. Multi-page imports working beautifully!
