### ISSUE TITLE
Question: Stack trace on WARNING expected?

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/ruby-vips#106]
When loading a TIF that lacks resolution information, VIPS issues warning as expected but also dumps a stack trace. Is this expected?

```
VIPS-WARNING **: no resolution information for TIFF image "multi-page-526x351x81-u8.tif" -- defaulting to 1 pixel per mm
	from ~/.gem/ruby/2.4.0/gems/gobject-introspection-3.1.1/lib/gobject-introspection/loader.rb:530:in `block in define_method'
	from ~/.gem/ruby/2.4.0/gems/ruby-vips-1.0.4/lib/vips/call.rb:183:in `build'
	from ~/.gem/ruby/2.4.0/gems/ruby-vips-1.0.4/lib/vips/call.rb:249:in `invoke'
	from ~/.gem/ruby/2.4.0/gems/ruby-vips-1.0.4/lib/vips/call.rb:278:in `call_base'
	from ~/.gem/ruby/2.4.0/gems/ruby-vips-1.0.4/lib/vips/image.rb:395:in `method_missing'
	...
```

**Comment by jcupitt** [comment]
I think that's just the default behaviour for the glib log handler under Ruby. I found this in the ruby-gnome2 source:

https://github.com/ruby-gnome2/ruby-gnome2/blob/master/glib2/ext/glib2/rbglib_messages.c#L60

It looks like calling `GLib::Log.cancel_handler()` might stop the message.

**Comment by harukizaemon** [comment]
Ahh fascinating. Thanks. I hadn't seen it before so I thought perhaps something had changed. I'll dig in to that.
