### ISSUE TITLE
How to get values of the histogram?

### ISSUE THREAD

**Issue by raimondasv** [jcupitt/ruby-vips#113]
Hi,

I'm trying to get histogram values as a ruby array of numbers and my approach seems to be very inefficient.

```ruby
require 'open-uri'
require 'vips'
require 'benchmark'

buffer = open('https://raw.githubusercontent.com/wiki/jcupitt/libvips/images/lanczos3.png').read
image = Vips::Image.new_from_buffer(buffer, '')

hist_img = image.hist_find.hist_cum.hist_norm

Benchmark.bm do |x|
  x.report('save to buffer ') { hist_img.jpegsave_buffer(Q: 99) }
  x.report('getpoint * 256') { hist_img.width.times.map { |index| hist_img[0].getpoint(index, 0) } }
  x.report('to_a ') { hist_img[0].to_a }
end
```
Output:
```
save to buffer   0.010000   0.000000   0.010000 (  0.010578)
getpoint * 256  1.370000   0.110000   1.480000 (  1.471586)
to_a   1.120000   0.010000   1.130000 (  1.131997)
```
It seems, converting histogram to a jpeg image and saving it to a buffer is 10 times faster than converting to an array. `to_a` actually calls `getpoint` many times internally and getpoint'a ruby implementation is more than a workaround than a solution.

Any help is appreciated.

**Comment by jcupitt** [comment]
Hello, you're right, `to_a` will not be quick. 

How about writing the histogram to a buffer and then using String#unpack? That ought to be quick, I think.

**Comment by jcupitt** [comment]
Sorry, not a buffer, I mean `write_to_memory`:

```
$ irb 
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.new_from_file "k2.jpg"
=> #<Vips::Image:0x5653962509c8 ptr=0x565396968010>
irb(main):003:0> y = x.hist_find
=> #<Vips::Image:0x5653961fb8d8 ptr=0x5653969681a0>
irb(main):004:0> y.format
=> #<Vips::BandFormat uint>
irb(main):005:0> z = y.write_to_memory
=> [203, 37, 0, 0, 79 ...
irb(main):010:0> z.pack('c*').unpack('i*')
=> [9675, 14927, 11367, 9948, 13234, 5591, 10128, ...
```

That's an RGB image, so it really needs repacking as `[[9675, 14927, 11367], [9948, 13234, 5591], ...`. Maybe there's a clever way to avoid the pack and then unpack as well?

**Comment by raimondasv** [comment]
Thank you, @jcupitt I'll give it a try.

Meanwhile, I figured out I just needed nth percentile value, so `Vips::Image.percent()` method is actually what I need.

@jcupitt - thank you again for your time, your work is very appreciated.

**Comment by jcupitt** [comment]
Glad you got it working. 

`.profile` is useful with histograms, it'll give you the index of the first non-zero element. You can write something like `(x.hist_find.hist_cum.hist_norm > 128).profile[1].getpoint(0, 0)` to find the 50% percentile, for example.

**Comment by jcupitt** [comment]
FYI there's a new version of the gem, 1.0.6, with a much faster `to_a` based on this issue.

**Comment by Nakilon** [comment]
> Glad you got it working.
> 
> `.profile` is useful with histograms, it'll give you the index of the first non-zero element. You can write something like `(x.hist_find.hist_cum.hist_norm > 128).profile[1].getpoint(0, 0)` to find the 50% percentile, for example.

Excuse me, I suppose this would be useful for me in the thing I'm into right now but I barely understand what's going on here. Can you explain? As I understand the `hist_find` creates an Image that is being used as a histogram array. Then for some reason only after it you can call `hist_norm`, right? So this method just expects 1 dimensional array to run some `fold_list` function over it, ok. Then the `hist_norm` expects 1 dimensional array to make it 0..255. But what does the `profile` do? Is it pixel sorting per line and per column?

**Comment by jcupitt** [comment]
Given a 2D image, `profile` searches in from the left and top edges for the first non-zero pixel. It returns a pair of 1D images with the distance to that non-zero pixel.

For example:

```
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.mask_ideal 64, 64, 0.5, optical: true, uchar: true, reject: true
=> #<Image 64x64 uchar, 1 bands, multiband>
irb(main):003:0> x.write_to_file "x.png"
=> nil
```

To make:

![x](https://user-images.githubusercontent.com/580843/71728154-36c0bf00-2e34-11ea-9e9f-46a71465e4d9.png)

Now:

```
irb(main):005:0> x.profile
=> [#<Image 64x1 int, 1 bands, histogram>, #<Image 1x64 int, 1 bands, histogram>]
```

The first 1D image is the down distances (distance down from the top edge to hit the first non-zero pixel):

```
irb(main):006:0> x.profile[0].to_a
=> [[[64], [64], [64], [64], [64], [64], [64], [64], [64], [64], [64], [64], [64], [64], [64], [64], [32], [27], [25], [23], [22], [21], [20], [19], [19], [18], [18], [17], [17], [17], [17], [17], [16], [17], [17], [17], [17], [17], [18], [18], [19], [19], [20], [21], [22], [23], [25], [27], [32], [64], [64], [64], [64], [64], [64], [64], [64], [64], [64], [64], [64], [64], [64], [64]]]
```

You can probably see that's the top semicircle of that circle.

A histogram is just a 1D image:

```
irb(main):008:0> x = Vips::Image.new_from_file "/home/john/pics/k2.jpg"
=> #<Image 1450x2048 uchar, 3 bands, srgb>
irb(main):009:0> x.hist_find
=> #<Image 256x1 uint, 3 bands, histogram>
```

So searching in from the left edge will give you the index of the first non-zero bucket:

```
irb(main):011:0> x.hist_find.profile[1].getpoint(0, 0)
=> [0.0, 0.0, 0.0]
```

In that example, we're running a conditional over the image first (is pixel >50th percentile), so the index is the pixel value.
