### ISSUE TITLE
add something to control glib log output

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/ruby-vips#119]
I'm not sure if this is a libvips or ruby-vips problem, but suppressing warnings by setting the `VIPS_WARNING` environment variable to `0` no longer works.

Instead every warning is printed with a complete backtrace:

```
VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
	from /Users/felix/.rvm/gems/ruby-2.4.1/gems/gobject-introspection-3.1.8/lib/gobject-introspection/loader.rb:576:in `block in define_method'
	from /Users/felix/.rvm/gems/ruby-2.4.1/gems/ruby-vips-1.0.6/lib/vips/call.rb:185:in `build'
	from /Users/felix/.rvm/gems/ruby-2.4.1/gems/ruby-vips-1.0.6/lib/vips/call.rb:253:in `invoke'
	from /Users/felix/.rvm/gems/ruby-2.4.1/gems/ruby-vips-1.0.6/lib/vips/call.rb:282:in `call_base'
	from /Users/felix/.rvm/gems/ruby-2.4.1/gems/ruby-vips-1.0.6/lib/vips/image.rb:632:in `write_to_file'
…
```

I'm using ruby-vips 1.0.6 and gobject-introspection 3.1.8  with vips 8.5.6 on ruby 2.4.1.

**Comment by felixbuenemann** [comment]
Oh, I guess it could be caused by jcupitt/libvips#544.

**Comment by jcupitt** [comment]
Hi Felix, yes, libvips is now using `g_warning()` for this stuff. I'll see if I can find a workaround. You're right, there should be some compat thing for this.

**Comment by jcupitt** [comment]
In C, you add:

```C
        g_log_set_handler( "VIPS", G_LOG_LEVEL_WARNING, my_log_handler, NULL );
```

somewhere just after startup to direct all warning messages to `my_log_handler`, perhaps:

```C
static void
my_log_handler( const gchar *log_domain, GLogLevelFlags log_level,
        const gchar *message, gpointer user_data )
{       
}
```

to print nothing.

I'm trying to find the equivalent for Ruby. The default handler installed by ruby-gnome2 is obviously to print a backtrack.

**Comment by jcupitt** [comment]
I can't get the obvious Ruby things to work :( so I added a hack to `vips_init()` in 8.5. It seems to work:

```
john@kiwi:~/try$ ./try254.rb  ~/pics/broken2.png
VIPS-WARNING **: Read Error
	from /home/john/packages/gems/gems/gobject-introspection-3.1.8/lib/gobject-introspection/loader.rb:576:in `block in define_method'
.... many, many lines of output trimmed
h = 11.0
s = 32.0
v = 178.0
john@kiwi:~/try$ export VIPS_WARNING=1
john@kiwi:~/try$ ./try254.rb  ~/pics/broken2.png
h = 11.0
s = 32.0
v = 178.0
```

**Comment by felixbuenemann** [comment]
I have done some experimenting with `GLib::Log.cancel_handler` and `GLib::Log.set_handler`, but so far all I achieved was resetting to the default handler, which does not print the backtrace using `GLib::Log.cancel_handler`. The `set_handler` installs the built-in handler for a given domain and log level, but I've yet to find out how to remove a handler, because the `remove_handler` method required a handler id, that I'm not sure how to obtain…

**Comment by felixbuenemann** [comment]
@jcupitt I don't think ruby-gnome2 currently provides an api for setting your own log handlers, so supporting the VIPS_WARNING and VIPS_INFO environment variables is probably the best idea. It also makes sure existing programs keep working as expected when upgrading to libvips 8.5+.

**Comment by jcupitt** [comment]
Yes, I poked about in ruby-gnome2 as well and I couldn't find any working API for this :( 

Hopefully the new ruby-vips can handle this in a better way.

**Comment by felixbuenemann** [comment]
Yeah, I've yet to try out the new ffi-based ruby-vips, but it's on my todo because it should save me a ton of build dependencies (gobject-introspection-dev pulls in half of x11 through cairo-dev).

**Comment by felixbuenemann** [comment]
I installed a version of libvips 8.5.7 with the patch from [this gist](https://gist.github.com/00c6e802b25a413e298187fc7ec99ee5) and it seems to work fine.

Should we leave this issue open, until there is a better solution in ruby-vips?

**Comment by jcupitt** [comment]
Good idea. The new ruby-vips ought to have something for this too.

**Comment by jcupitt** [comment]
I've added something to pyvips to redirect libvips warnings to the standard Python logging module. It's a nice simple thing and seems to work well.

https://github.com/jcupitt/libvips/issues/715#issuecomment-324356680

How about doing the same for Ruby? Would a redirect to `logger` be OK?

**Comment by felixbuenemann** [comment]
The common way in Ruby would be to have a class accessor like ˋVips.loggerˋ which defaults to something like ˋLogger.new(STDOUT)ˋ but can be overridden by assigning a diffferent logger instance, eg. ˋVips.logger = Rails.loggerˋ. You could also control the log level through ˋVips.logger.levelˋ.

**Comment by jcupitt** [comment]
I had a go, does that look reasonable? Usage:

```ruby
require 'vips'
GLib::logger = some other logger
GLib::logger.level = Logger::ERROR
```

It'll show warnings by default, same as now. ruby-vips debug messages come out the same way, so `GLib::logger.level = Logger::DEBUG` is very chatty.

**Comment by felixbuenemann** [comment]
Yes, that's what I meant.

I would advise you to move the `GLib` and `GObject` modules into the `Vips` namespace, so they don't clash with constants from existing gems in the global namespace:

```ruby
module Vips
  module GLib
    …
  end
  module GObject
    …
  end
end
```

None of your code should have to change because of that, because ruby's constant lookup will automatically use `Vips::GLib` or `Vips::GObject` if you reference `GLib`or `GObject` from inside the `Vips` module, unless you specifically used `::GLib` or `::GObject` to refer to the top-level constant.

**Comment by felixbuenemann** [comment]
Oh and I just noticed that `Logger` has an instance method called `#add` and aliased as `#log`, so you could replace `@logger.send(GLIB_TO_SEVERITY[level], domain) {message}` with `@logger.log(GLIB_TO_SEVERITY[level], message, domain)` (and changing `GLIB_TO_SEVERITY` to point to the `Logger::<LEVEL>` constants) which should have a little less overhead due to not needing to allocate a proc for each log message.

**Comment by jcupitt** [comment]
OK, thanks @felixbuenemann!

I'll try moving GLib and GObject inside Vips in another branch.
