### ISSUE TITLE
Dilate on grayscale images

### ISSUE THREAD

**Issue by luisrpp** [jcupitt/ruby-vips#120]
I'm trying to apply the dilate method on a grayscale image (lena.jpg btw), and I'm getting a white image as output.

Am I doing something wrong, or it works only on binary images?

This is what I did:

```ruby
SELEM_3X3 = [[128, 255, 128],
             [255, 255, 255],
             [128, 255, 128]]
 
image = Vips::Image.new_from_file('samples/lena.jpg').colourspace :grey16
image.dilate(SELEM_3X3).write_to_file('dilate.png')
```

Thanks,
Luis

**Comment by jcupitt** [comment]
Hello, yes, things like dilate / erode only work on binary (zero / not-zero) images. You'd normally used a median filter and a threshold first. 

Rank filters are probably the best equivalent for greyscale images. Use minimum for erode, maximum for dilate.

**Comment by luisrpp** [comment]
Thanks!! I'll try that!

Best regards
