### ISSUE TITLE
Converting an image to grayscale

### ISSUE THREAD

**Issue by luisrpp** [jcupitt/ruby-vips#121]
Hi,

Is there a better way to convert an image to grayscale than the example presented bellow?

```ruby
module ImageRefinements
  refine Vips::Image do
    def to_grayscale
      colourspace(:grey16)[0]
    end
  end
end
```

I want to preserve the format of the original image. How can I do that?

Thanks,
Luis

**Comment by jcupitt** [comment]
Hello, do you mean you want an 8-bit source to be an 8-bit greyscale, and a 16-bit source a 16-bit greyscale?

You could do:

```
irb(main):003:0> require 'vips'
=> true
irb(main):004:0> x = Vips::Image.new_from_file "k2-16.png"
=> #<Image 1450x2048 ushort, 3 bands, rgb16>
irb(main):009:0> if x.format == :uchar then x.colourspace :b_w else x.colourspace :grey16 end
=> #<Image 1450x2048 ushort, 1 bands, grey16>
```

**Comment by luisrpp** [comment]
Thanks!

I thought there was a more straightforward method, but this will work!

Best regards,
Luis

**Comment by jcupitt** [comment]
It can be a little awkward, but having separate colourspaces for 8 and 16-bit greyscale means you always know the numeric range. All the libvips spaces are like this: you can just look at `.interpretation` and know what arithmetic calculation on that image will do to the colour.
