### ISSUE TITLE
error when attempting to read EXIF orientation

### ISSUE THREAD

**Issue by tomasc** [jcupitt/ruby-vips#122]
@jcupitt perhaps something to do with the `ffi` rewrite?

```ruby
img = Vips::Image.new_from_file('FOO.JPG')
img.get("exif-ifd0-Orientation")
Vips::Error: unimplemented gtype for get: 140194323501504
	from /.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ruby-vips-2.0.0/lib/vips/gvalue.rb:211:in `get'
	from /.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ruby-vips-2.0.0/lib/vips/image.rb:492:in `get'
```

**Comment by tomasc** [comment]
PS the `autorotate` flag works correctly

**Comment by kleisauke** [comment]
Try this:
```ruby
require 'vips'

img = Vips::Image.new_from_file('FOO.JPG')

# Check if it has a orientation tag
if img.get_typeof("orientation") != 0
    # Output the int from 1 - 8 using the standard exif/tiff meanings
    puts img.get("orientation")
else
    puts "No orientation tag"
end
```

Not long ago I had the same problem (with php), see: https://github.com/jcupitt/php-vips/issues/13#issuecomment-252412013.

**Comment by jcupitt** [comment]
Kleis is right, the `orientation` tag is the new official way to do this. 

But using the ifd should have worked too, it sounds like a case might  be missing from the thing to read values. I'll have a look.

**Comment by jcupitt** [comment]
Yes, the vips reference counted string gtype was missing. I now see:

```
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.new_from_file "/home/john/pics/k2.jpg"
=> #<Image 1450x2048 uchar, 3 bands, srgb>
irb(main):003:0> x.get("exif-ifd0-Orientation")
=> "1 (Top-left, Short, 1 components, 2 bytes)"
```

I'll add a test and push a new version. Thanks for reporting this dumbness!

**Comment by jcupitt** [comment]
v2.0.1 push to rubygems

**Comment by tomasc** [comment]
Wonderful, thanks! I will give it a test right now.

**Comment by tomasc** [comment]
Just to confirm, all works fine now. Thanks again.
