### ISSUE TITLE
FFI::NotFoundError (vips 8.3.3)

### ISSUE THREAD

**Issue by zverok** [jcupitt/ruby-vips#128]
```
$ gem which vips
/home/zverok/.rvm/gems/ruby-2.3.3/gems/ruby-vips-2.0.3/lib/vips.rb
$ vips -v
vips-8.3.3-Thu Aug 18 19:23:54 UTC 2016
$ irb -rvips
/home/zverok/.rvm/gems/ruby-2.3.3/gems/ffi-1.9.18/lib/ffi/library.rb:275:in `attach_function':FFI::NotFoundError: Function 'vips_image_get_fields' not found in [libvips.so]
```

:(

**Comment by jcupitt** [comment]
Ooops, OK, that function was added in libvips 8.5.

I'll add a test. Thanks for reporting this dumbness!

**Comment by zverok** [comment]
:+1: 

Playing a lot with ruby graphics ([1](https://github.com/zverok/magic_cloud), [2](https://github.com/zverok/worldize), [3](https://github.com/zverok/drosterize)), I am really tired of RMagick and can't wait for playing with this new shiny thing :)

**Comment by jcupitt** [comment]
OK, new version pushed. Thanks again for the report.

I noticed another issue with older libvips: it's not reporting enums as symbols. With libvips 8.5, you see:

```
>>> image.format 
:uchar
```

But with 8.4 it's coming out as an int. I'll see if I can fix this, but it might be better to update to 8.5 in the meantime if you can .

**Comment by jcupitt** [comment]
issue for the enum problem https://github.com/jcupitt/ruby-vips/issues/129

**Comment by zverok** [comment]
> I'll see if I can fix this, but it might be better to update to 8.5 in the meantime if you can.

Latest Ubuntu stable package is 8.3.3, and I at the moment am not ready to compile libvips myself ¯\\\_(ツ)_/¯

**Comment by jcupitt** [comment]
OK, I'll test with 8.3 too.

**Comment by jcupitt** [comment]
I've pushed 2.0.5, it should fix the enums. Works with 8.3 - 8.6, it should work with 8.2 as well.

**Comment by zverok** [comment]
Thanks! Works now!

**Comment by jcupitt** [comment]
I like your image processing experiments. libvips can't write gifs, so you'd need to make them as a set of frames and later assemble as video with magick or mencoder (I guess).

You can do the warping with mapim, this has an example:

https://github.com/jcupitt/ruby-vips/blob/master/example/wobble.rb

It makes this:

http://2.bp.blogspot.com/-_ZipOkEp-XM/Vk9W9UaydvI/AAAAAAAAAvY/Hax_kKfIz2g/s1600/x.jpg

Some background:

http://libvips.blogspot.co.uk/2015/11/fancy-transforms.html

**Comment by jcupitt** [comment]
(that blog post is in Python, of course, but the Ruby one is almost the same)
