### ISSUE TITLE
`write_to_file` hangs

### ISSUE THREAD

**Issue by tomasc** [jcupitt/ruby-vips#131]
(not sure how better to call this issue, sorry)

I am running into issues when processing [this image](https://www.dropbox.com/s/3164hibygwhfapf/test.tif?dl=0) (125MB TIFF)

`vipsthumbnail` cli works fine:

```
$ vips --version
vips-8.5.8-Thu Sep  7 18:55:56 CEST 2017

$ vipsthumbnail test.tif -s 200 -o test.jpg
(vipsthumbnail:5551): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
(vipsthumbnail:5551): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
(vipsthumbnail:5551): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
(vipsthumbnail:5551): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
(vipsthumbnail:5551): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
(vipsthumbnail:5551): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
(vipsthumbnail:5551): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
(vipsthumbnail:5551): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored

$ open test.jpg
```

However when trying to process the same image file in `ruby-vips`, `write_to_file` or `write_to_buffer` just hangs the whole Ruby process.

I am on `ruby 2.3.3p222` and `ruby-vips 2.0.6` on OS X. Same thing happens on Linux as well.

```ruby
img = Vips::Image.thumbnail('test.tif', 200)
img.write_to_file('test.jpg')
```

(Also tried `Vips::Image.new_from_file`, same result.)

**Comment by jcupitt** [comment]
Looks like it's a problem with FFI locking: the TIFF loader is trying to log a warning from a worker thread.

**Comment by tomasc** [comment]
Please let me know if I can help anyhow.

**Comment by jcupitt** [comment]
The problem was libvips background worker threads trying to report warnings. The sequence of events was:

* Ruby calls a vips operation, like `write_to_file`
* the Ruby thread waits for libvips to come back, and holds the FFI lock while it does it
* a worker thread inside libvips sees an error and tries to log it
* the log handler tries to call back to Ruby to send the message on to `Logger`
* ... but the lock is being held by the main Ruby thread, so deadlock.

To fix this, we probably need to get all g_log() output to happen on the main libvips thread. This is a big change to libvips :( I'll have a think.

In the meantime, I've disabled all the logging stuff and updated the docs. Could you try 2.0.7?

**Comment by tomasc** [comment]
Hi John, thank you very much, things work fine on `2.0.7`.

And it does log out the same warnings (which I assume is a good thing):

```
(test.rb:15084): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
(test.rb:15084): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
(test.rb:15084): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
(test.rb:15084): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
(test.rb:15084): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
(test.rb:15084): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
(test.rb:15084): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
(test.rb:15084): VIPS-WARNING **: Incompatible type for "RichTIFFIPTC"; tag ignored
```

**Comment by jcupitt** [comment]
Oh good, I'm glad it works. Define the env var `VIPS_WARNING=1` to hide the warnings, if you like.

**Comment by kelilevi** [comment]
I am getting a lot of VIPS-WARNING if the file is saved from Photoshop; how I can hide the warnings in ruby-vips? I see I need to define the env var VIPS_WARNING = 1, but I don't know how and where to do that. Any help appreciated.

**Comment by jcupitt** [comment]
I think you can do:

```ruby
ENV["VIPS_WARNING"] = 1
```

somewhere in your startup.

**Comment by kelilevi** [comment]
Worked with ENV["VIPS_WARNING"] = '1'
Thank you John!!!
