### ISSUE TITLE
Can't save as image with unusual extension

### ISSUE THREAD

**Issue by Nakilon** [jcupitt/ruby-vips#133]
I would like to save some temporal files with extension `.temp` but I get `No known saver for '1.temp'. (Vips::Error)`

Thing like this would be nice:

```ruby
def write_to_file name, type = nil, opts = {}
  ...
  saver = Vips::vips_foreign_find_save(type || filename)
```
```ruby
im.write_to_file "1.temp", "png"
```

**Comment by jcupitt** [comment]
Hello, `write_to_file` uses the extension to decide what saver to use, so it has to be a known extension.

You can call `pngsave` directly, for example:

```
im.pngsave "1.temp"
```

Would that work?

**Comment by Nakilon** [comment]
Yeah seems to work fine. Thanks.
