### ISSUE TITLE
How to resample or add background to an Image

### ISSUE THREAD

**Issue by GustavoCaso** [jcupitt/ruby-vips#134]
I'm quite new in the image process world :) but I'm trying to achieve some similar commands that imagemagick have like `resample`, is there any specific method in the library for it?

Also, I'm looking for a way of adding a background to an image, is this possible? If so what could method I could use and how to create colors in `ruby-vips`.

Thank you for your time and great library 💪

**Comment by jcupitt** [comment]
Hi again, you can resize images with `resize`:

http://www.rubydoc.info/gems/ruby-vips/Vips/Image#resize-instance_method

If you want to thumbnail an image from disc or memory, there's a handy method which picks the best technique for you:

http://www.rubydoc.info/gems/ruby-vips/Vips/Image#thumbnail-class_method

The C docs have more detail:

http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail

What do you mean by adding background? Do you want to add a border to an image? `embed` is the operator:

http://www.rubydoc.info/gems/ruby-vips/Vips/Image#embed-instance_method

**Comment by GustavoCaso** [comment]
Thanks for the quick answer :)

What I mean with adding a background when resizing an image pad the remaining area with a background color. 

I'm adding a ruby-vips to an image processing library and I'm trying to add the same API the have but they currently use imagemagick

This is the example for `resize_and_pad` https://github.com/janko-m/image_processing/blob/master/lib/image_processing/mini_magick.rb#L141

Also I'm looking in how to add the concept of `gravity`  when cropping an image

**Comment by jcupitt** [comment]
Ah OK, yes, you want `embed`.

You have to do the gravity stuff yourself for now, it's only a few lines. The next version (or the one after?) should have a `gravity` operator.

libvips has smartcrop built in, it might be fun to expose that. 

Good luck with your project, it sounds fun. Let me know if you have any other problems.

**Comment by GustavoCaso** [comment]
Can you show me an example of a gravity?

**Comment by jcupitt** [comment]
To crop left / top / width / height from an image with gravity NORTH:

```ruby
image = image.crop (image.width - width) / 2, 0, width, height
```

You just need 8 lines like that for the 8 cases.

**Comment by jcupitt** [comment]
Oh, 9 cases with centre I guess.

**Comment by GustavoCaso** [comment]
Thanks for the answer @jcupitt. Maybe I'm not very familiar with the cropping and gravity but why is that calculation for NORTH?

**Comment by jcupitt** [comment]
It'll crop out a rectangle centred on the top edge, try it. 

If you use `embed` instead of `crop`, you'll find it does the inverse: it adds a border around the sides and bottom, leaving the image centred on the top edge. 

By coincidence I'm adding a gravity operator for 8.6 now. You can see the cases here:

https://github.com/jcupitt/libvips/blob/gargsms-text-autofit/libvips/conversion/embed.c#L730

**Comment by GustavoCaso** [comment]
I tried it :) it does that!

What confuse me or the question I was asking is what would be the value for the rest of the gravity options? Also I know I have to play more with the library and really appreciate your help on this one.

For the crop option now I'm using `extract_area` with this parameters 
```ruby
def crop!(img, width, height, x_offset=0, y_offset=0)
  width   ||= img.width
  height  ||= img.height
  top       = x_offset.is_a?(Float)  && x_offset.between?(0,1)  ? (img.height - height) * x_offset : 
  x_offset
  left      = y_offset.is_a?(Float) && y_offset.between?(0,1) ? (img.width - width) * y_offset : y_offset
  img = img.extract_area left, top, width, height
end
```

So far is giving a good output. I found this on other libraries that use `ruby-vips` where the `left` and `top` are `Float` would work as `offset` and if send as `Integer` would be different

Maybe ther is a better way for this.

**Comment by jcupitt** [comment]
Hmm I'm not sure I like that. It's easy to pass a float by mistake, and then very strange things will happen if you try to crop a single pixel out.

I would have two crop operators: `crop!` and `crop_percent!` (or `crop_ratio!` maybe?). Up to you, of course.

**Comment by GustavoCaso** [comment]
Well I'm trying to achieve a similar result from Imagemagick.

Imagemagick crop function allows passing the width and height, the offset values and the gravity as well. I should probably use multiple commands from `ruby-vips`. Maybe first resize them crop? 

Which commands would you use to match as much as possible what is able to do with imagemagick?

**Comment by jcupitt** [comment]
Paste the exact IM command you need to replicate and I'll have a go at translation.

**Comment by GustavoCaso** [comment]
`convert -crop #{width}x#{height}+#{x_offset}x#{y_offset} -gravity #{gravity}`

Been the gravity one of the valid form Imagemagick `NorthWest, North, NorthEast, West, Center, East, SouthWest, South, SouthEast`

Thank you so much. Is amazing how helpful you are 😄

**Comment by jcupitt** [comment]
The `x_offset` and `y_offset` there are not used, the IM command should be:

```
convert  #{input_file} -gravity #{gravity} -crop #{width}x#{height}+0x0 #{output_file}
```

You need the gravity first, and the offsets should be zero. 

The ruby-vips equivalent would be:

```ruby
def crop_gravity image, gravity, width, height
  case gravity
    when :north
      image.crop (image.width - width) / 2, 0, width, height
    when :south
      ...
  end
end
```

Don't be too impressed :( I'm only responsive because I'm working on libvips at the moment, I'd be very distracted if I were on a different project.

**Comment by GustavoCaso** [comment]
Awesome @jcupitt thanks. I will keep working and if I have any question I will ask.

One last thing I guess for `south` gravity would be `0, (image.width - width) / 2` ?

**Comment by jcupitt** [comment]
South would be `(image.width - width) / 2, height - image.height`. You can see all the cases here:

https://github.com/jcupitt/libvips/blob/gargsms-text-autofit/libvips/conversion/embed.c#L730

**Comment by GustavoCaso** [comment]
Fantastic!!!!!!!! I will send you the final code when is done but you have help me more than enough

**Comment by GustavoCaso** [comment]
@jcupitt is there a way of controlling the resolution when using `resize`?

**Comment by GustavoCaso** [comment]
I'm looking into `copy` and then `resize`.

How would you calculate the scale value of `resize` base on the `witdh` and `height` provided?

```ruby
def resample!(image, width, height)
      with_ruby_vips(image) do |img|
        img = img.copy(xres: width, yres: height)
        img = resize_image img, width, height
        tmp_name = tmp_name(image.path)
        img.write_to_file(tmp_name)
        tmp_name
      end
    end

   def resize_image(image, width, height, min_or_max = :min)
      ratio = get_ratio image, width, height, min_or_max
      return image if ratio == 1
      image = if ratio > 1
                image.resize(ratio, kernel: :nearest)
              else
                image.resize(ratio, kernel: :cubic)
              end
      image
    end

    def get_ratio(image, width,height, min_or_max = :min)
      width_ratio = width.to_f / image.width
      height_ratio = height.to_f / image.height
      [width_ratio, height_ratio].send(min_or_max)
    end
```

**Comment by GustavoCaso** [comment]
@jcupitt I promise is the last question :) Sorry for asking so much.

I'm playing with `embed` and I having some problem understanding how to use the `x` and `y` coordinates.

So far I have this method.

```ruby
def resize_and_pad!(image, width, height, background: "transparent", gravity: "Center")
      with_ruby_vips(image) do |img|
        img = resize_image img, width, height
        top, left = get_gravity_values(img, width, height, gravity)
        img = img.embed(top, left, width, height, {extend: :background, background: get_background(background)})
        tmp_name = tmp_name(image.path)
        img.write_to_file(tmp_name)
        tmp_name
      end
    end

def resize_image(image, width, height, min_or_max = :min)
      ratio = get_ratio image, width, height, min_or_max
      return image if ratio == 1
      image = if ratio > 1
                image.resize(ratio, kernel: :nearest)
              else
                image.resize(ratio, kernel: :cubic)
              end
      image
    end

    def get_ratio(image, width,height, min_or_max = :min)
      width_ratio = width.to_f / image.width
      height_ratio = height.to_f / image.height
      [width_ratio, height_ratio].send(min_or_max)
    end

def get_background(background)
      case background.downcase
      when "red"
        [255,0,0]
      when "green"
        [0,255,0]
      when "blue"
        [0,0,255]
      end
    end

    def get_gravity_values(image, width, height, gravity)
      top = image.width - width
      left = image.height - height
      case gravity
        when 'Center'
          [(top / 2), (left / 2)]
        when 'North'
          [(top / 2), 0]
        when 'East'
          [top, (left / 2)]
        when 'South'
          [(top / 2), left]
        when 'West'
          [0, (left / 2)]
        when 'NorthEast'
          [top, 0]
        when 'SouthEast'
          [top,left]
        when 'SouthWest'
          [0, left]
        when 'NorthWest'
          [0, 0]
        else
          raise InvalidGravityValue
      end
    end
``` 
The imput image is:
![image](https://user-images.githubusercontent.com/4672858/30730533-2023f4fe-9f68-11e7-8ecc-22273fc2fcfe.png)

The expected aoutput is:
![image](https://user-images.githubusercontent.com/4672858/30730538-2b6eb77c-9f68-11e7-8611-8df576c158c6.png)

But the output I get is:
![image](https://user-images.githubusercontent.com/4672858/30730591-797ca050-9f68-11e7-975e-fdf3c610b83e.png)


I'm Sure it has to do with `x` and `y` values used in embed, but I'm not able to figure out the math to calculate the good values.

**Comment by jcupitt** [comment]
Hello, you have left and top swapped in embed -- it's always horizontal before vertical. 

Try:

```ruby
        img = img.embed(left, top, width, height, {extend: :background, background: get_background(background)})
```

**Comment by GustavoCaso** [comment]
Really OMG feel stupid right now :) Thanks for that I will try later

**Comment by janko-m** [comment]
The `libvips` branch of the image_processing gem is now using `Vips::Image#gravity`, so this issue can probably be closed.

By the way, I'm very impressed with all the recent features of `libvips`, especially the `vipsthumbnail` and `gravity` functionality, it allowed us to remove a lot of custom Ruby code 🙏
