### ISSUE TITLE
Getting `g_signal_emit_valist: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed` when actively use `draw_line`

### ISSUE THREAD

**Issue by Nakilon** [jcupitt/ruby-vips#140]
```
(test.rb:93224): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(test.rb:93224): GLib-GObject-CRITICAL **: g_signal_emit_valist: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(test.rb:93224): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(test.rb:93224): GLib-GObject-CRITICAL **: g_signal_emit_valist: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(test.rb:93224): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(test.rb:93224): GLib-GObject-CRITICAL **: g_signal_emit_valist: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```
Program seems to produce valid images, but there are warnings printed. So I minified my program as much possible to reproduce it:
```
$ cat Gemfile
source "https://rubygems.org"
ruby "2.0.0"

gem "ruby-vips"
```
```
$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    ffi (1.9.18)
    ruby-vips (2.0.7)
      ffi (~> 1.9)

PLATFORMS
  ruby

DEPENDENCIES
  ruby-vips

RUBY VERSION
   ruby 2.0.0p648

BUNDLED WITH
   1.15.4
```
Mac OS
```ruby
require "vips"

a, b = Array.new(2).map{ |f| Vips::Image.new_from_file "../images/1d468d064d2e26b5b5de9a0241ef2d4b.jpg" }.map do |image|
  image = image.draw_line 0, 0, 1, 0, 2
  image
end

a, b = [a, b].map do |image|
  45.times do
    image = image.draw_line 0, 0, 1, 0, 2
  end
  image
end

a.join(b, :horizontal, expand: true).write_to_file "ab.jpg"
```
Warnings will disappear if I decrease the number `45` or if I remove the first `.draw_line` call. Also when I use `Vips::Image.blank 1000, 1000` instead of a real file, and some images cause this issue, some are not. Also they were disappearing even depending on the number of lines in this source file. Or when I used `Array.new(2)` instead of `ARGV` passing two arguments, etc.
Probably you will need try different images or increase the number of `image = image.draw_line` lines to execute.

**Comment by jcupitt** [comment]
I made a slight variation :

```ruby
require "vips"

a = b = Vips::Image.new_from_file "/home/john/pics/k2.jpg"
a = a.draw_line 0, 0, 1, 0, 2
b = b.draw_line 0, 0, 1, 0, 2

a, b = [a, b].map do |image|
    30.times do |i|
        puts "iteration #{i} .."
        image = image.draw_line 0, 0, 1, 0, 2
    end
    image
end

puts "writing .."
a.join(b, :horizontal, expand: true).write_to_file "ab.jpg"
```

Make messages fatal with:

```
$ export G_DEBUG=fatal-warnings
```

And you can see it fails at different points each time, and with slightly different messages, which is interesting. 

gdb shows that it's perhaps something to do with progress feedback system.

**Comment by jcupitt** [comment]
Commenting out this line:

https://github.com/jcupitt/libvips/blob/master/libvips/foreign/foreign.c#L813

Seems to fix it. I'll investigate.

Thanks for the report!

**Comment by jcupitt** [comment]
I've pushed a proper fix to 8.5, it seems to work now. I'll do an 8.5.9 in the next day or so.

Thanks again for the report.

**Comment by Nakilon** [comment]
Nice. I use brew to install vips on Mac OS -- who updates the formula there?

**Comment by jcupitt** [comment]
I'm the main contact for the formula, but anyone can put in a PR, of course.

**Comment by jcupitt** [comment]
OK, 8.5.9 is up with this fix. You should just be able to edit your `vips.rb` formula.
