### ISSUE TITLE
Mac OS: LoadError: Could not open library 'vips'

### ISSUE THREAD

**Issue by Nakilon** [jcupitt/ruby-vips#141]
So I did `brew upgrade vips` that poured the `vips-8.5.8_2.el_capitan` and now `require vips` (the gem is the latest one) cause:
```
LoadError: Could not open library 'vips': dlopen(vips, 5): image not found.
Could not open library '/usr/local/lib/libvips.dylib': dlopen(/usr/local/lib/libvips.dylib, 5): Library not loaded: @rpath/libpoppler.71.dylib
  Referenced from: /usr/local/opt/poppler/lib/libpoppler-glib.8.dylib
  Reason: image not found
	from /Users/nakilon/.gem/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib'
	from /Users/nakilon/.gem/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `map'
	from /Users/nakilon/.gem/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `ffi_lib'
	from /Users/nakilon/.gem/gems/ruby-vips-2.0.7/lib/vips.rb:466:in `<module:Vips>'
	from /Users/nakilon/.gem/gems/ruby-vips-2.0.7/lib/vips.rb:457:in `<top (required)>'
```
```bash
$ ls -l /usr/local/lib/libvips.dylib
lrwxr-xr-x  1 nakilon  admin  40 11 окт 19:17 /usr/local/lib/libvips.dylib -> ../Cellar/vips/8.5.8_2/lib/libvips.dylib
$ ls -l /usr/local/lib/libpoppler.dylib 
lrwxr-xr-x  1 nakilon  admin  45 11 окт 19:17 /usr/local/lib/libpoppler.dylib -> ../Cellar/poppler/0.60.1/lib/libpoppler.dylib
```
Ruby is native to this OS: 2.0.0p648

The thing I've noticed about brew is that now it drags some portable Ruby 2.3 -- not sure if that's relevant.

**Comment by hmistry** [comment]
Have a look at #130 and try the suggestions... I think it's a bad install configuration issue and you need to track down where it went wrong.

**Comment by jcupitt** [comment]
I tried again here and it seems to be working on sierra at least:

```
==> Downloading https://homebrew.bintray.com/bottles/vips-8.5.8_2.sierra.bottle.
==> Downloading from https://akamai.bintray.com/89/89fdabb07d18ac3cf22448e1bbb6f
######################################################################## 100.0%
==> Pouring vips-8.5.8_2.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/vips/8.5.8_2: 188 files, 12.7MB
john@katamata ~ $ gem uninstall ruby-vips
Successfully uninstalled ruby-vips-2.0.6
john@katamata ~ $ gem install ruby-vips
Fetching: ruby-vips-2.0.7.gem (100%)
Successfully installed ruby-vips-2.0.7
Parsing documentation for ruby-vips-2.0.7
Installing ri documentation for ruby-vips-2.0.7
Done installing documentation for ruby-vips after 1 seconds
1 gem installed
john@katamata ~ $ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.black 10, 10
=> #<Image 10x10 uchar, 1 bands, b-w>
irb(main):003:0> 
```

**Comment by Nakilon** [comment]
$ which vips
/usr/local/bin/vips
$ vips --version
vips-8.5.8-Fri Oct  6 06:09:10 BST 2017
$ brew --prefix vips
/usr/local/opt/vips

$ gem uninstall ruby-vips
Select gem to uninstall:
 1. ruby-vips-1.0.3
 2. ruby-vips-2.0.7
 3. All versions
> 3
Successfully uninstalled ruby-vips-1.0.3
Successfully uninstalled ruby-vips-2.0.7
$ gem install ruby-vips
Fetching: ruby-vips-2.0.7.gem (100%)
Successfully installed ruby-vips-2.0.7
Parsing documentation for ruby-vips-2.0.7
Installing ri documentation for ruby-vips-2.0.7
1 gem installed

$ irb
irb(main):001:0> require "vips"
LoadError: Could not open library 'vips': dlopen(vips, 5): image not found.
Could not open library '/usr/local/lib/libvips.dylib': dlopen(/usr/local/lib/libvips.dylib, 5): Library not loaded: @rpath/libpoppler.71.dylib
  Referenced from: /usr/local/opt/poppler/lib/libpoppler-glib.8.dylib
  Reason: image not found
	from /Users/nakilon/.gem/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib'
	from /Users/nakilon/.gem/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `map'
	from /Users/nakilon/.gem/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `ffi_lib'
	from /Users/nakilon/.gem/gems/ruby-vips-2.0.7/lib/vips.rb:466:in `<module:Vips>'
	from /Users/nakilon/.gem/gems/ruby-vips-2.0.7/lib/vips.rb:457:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from (irb):1
	from /usr/bin/irb:12:in `<main>'

**Comment by Nakilon** [comment]
Putting debug prints into ffi I see it loads `libglib` and `libgobject` as dylibs from `/usr/local/lib/` but fails to load `libvips`.
```
$ file /usr/local/lib/libvips.dylib
/usr/local/lib/libvips.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```
What is poppler? Maybe it's smth with it?
```
$ file /usr/local/lib/libpoppler
libpoppler-cpp.0.3.0.dylib   libpoppler-cpp.dylib         libpoppler-glib.8.dylib      libpoppler.71.0.0.dylib      libpoppler.dylib
libpoppler-cpp.0.dylib       libpoppler-glib.8.9.0.dylib  libpoppler-glib.dylib        libpoppler.71.dylib  
```

**Comment by Nakilon** [comment]
Switching back via `$ brew switch vips 8.5.8`  does not help:
```
$ vips --version
dyld: Library not loaded: /usr/local/opt/poppler/lib/libpoppler-glib.8.dylib
  Referenced from: /usr/local/bin/vips
  Reason: Incompatible library version: vips requires version 18.0.0 or later, but libpoppler-glib.8.dylib provides version 8.0.0
Trace/BPT trap: 5
```

**Comment by Nakilon** [comment]
Applying patch from pull/144 (`usr` instead of `lib`) had no effect.

**Comment by Nakilon** [comment]
Weird stuff. Looking for a way to debug I found such tools as `dtrace` and similar. To make it work on modern Mac OS you have to avoid the SIP (that security thing that protects /usr/bin). One of the ways to do this is to copy the binary from `/usr/bin` to any another folder. So I've copied `ruby` and `irb` to another folder, edited the shebang in `irb`, ran it and guess what -- it does `require "vips"` and loads images with no problem.

**Comment by Nakilon** [comment]
Probably related: https://github.com/ros2/ros2/issues/391#issuecomment-333984976

**Comment by Nakilon** [comment]
So as workaround I've decided to copy a `ruby` executable to another directory -- for example, a working directory of where I need to run things. Like this:
```bash
$ sudo cp /usr/bin/ruby ./
$ chmod 500 ./ruby
```
Here is how I made things work:
### IRB
If you do `which irb` you'll see that it's a ruby script `/usr/bin/irb` that has hardcoded shebang `#!/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby` so instead of `irb` you have to do:
```bash
$ ./ruby irb
```
### RSPEC
`which rspec` gives me `/Users/nakilon/.gem/bin/rspec` and there we see the `#!/usr/bin/env ruby` that means you don't have to patch it, just:
```bash
$ PATH=`pwd`:$PATH rspec
```
### RAKE
This one is tricky -- rake runs rspec in another way and seems to use the system ruby. How to check it? The only working way to know the exact path to executable by PID on Mac OS I've found is https://stackoverflow.com/a/14805946/322020 so you compile it and put the tool nearby. You can see it's working by:
```bash
$ ruby -e 'puts `./pathfind #{Process.pid}`'
proc 19893: /usr/bin/ruby
$ PATH=`pwd`:$PATH ruby -e 'puts `pathfind #{Process.pid}`'
proc 19897: /Users/nakilon/.../ruby
$ PATH=`pwd`:$PATH /usr/bin/env ruby -e 'puts `pathfind #{Process.pid}`'
proc 19900: /Users/nakilon/.../ruby
```
Now at the bottom of vips issue backtrace we see `from /Users/nakilon/.gem/gems/rspec-core-3.5.3/exe/rspec:4`. Here its content:
```ruby
#!/usr/bin/env ruby

require 'rspec/core'
RSpec::Core::Runner.invoke
```
Right after shebang you add the following line for debug:
```ruby
puts __FILE__, `/Users/nakilon/.../pathfind #{Process.pid}`
```
Now when you run the rake again you see:
```
/Users/nakilon/.gem/gems/rspec-core-3.5.3/exe/rspec
proc 19849: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
```
that means shebang is ignored. Open the `/usr/bin/rake` and add the
```
require "byebug"
byebug
```
right before the `Rake.application.run` -- moving down with `step` and `next` commands you'll eventually get to:
```
[74, 83] in /Users/nakilon/.gem/gems/rspec-core-3.5.3/lib/rspec/core/rake_task.rb
   74:       # @private
   75:       def run_task(verbose)
   76:         command = spec_command
   77:         puts command if verbose
   78: 
=> 79:         return if system(command)
   80:         puts failure_message if failure_message
   81: 
   82:         return unless fail_on_error
   83:         $stderr.puts "#{command} failed" if verbose
(byebug) command
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I/Users/nakilon/.gem/gems/rspec-support-3.5.0/lib:/Users/nakilon/.gem/gems/rspec-core-3.5.3/lib /Users/nakilon/.gem/gems/rspec-core-3.5.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
```
where the `spec_command` was:
```
   141:       def spec_command
   142:         cmd_parts = []
   143:         cmd_parts << RUBY
   144:         cmd_parts << ruby_opts
   145:         cmd_parts << rspec_load_path
```
The `RUBY` constant isn't declared at the moment the byebug starts but it appears immediately after you step into `Rake.application.run`. If you do the
```bash
$ grep -rI "RUBY =" /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/
```
you'll find the `RUBY = ENV['RUBY'] || File.join(` in `file_utils.rb` that is required by `/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake.rb`. So the solution is just:
```bash
$ RUBY=`pwd`/ruby rake
```

**Comment by jcupitt** [comment]
Thank you for writing this @Nakilon, it's very helpful.

I guess another solution would be to recommend the homebrew Ruby, is that right?

**Comment by Nakilon** [comment]
Since the issue didn't exist earlier, I think smth is broken and can be fixed. Maybe some updated dependency does not meet modern Mac OS practices. That's not nice to force people to use another Ruby or disable SIP.

**Comment by Nakilon** [comment]
Update to previous comment.
This
```bash
bundle exec ./ruby `which irb`
```
seems to stop working if you install rbenv. In this case you should do:
```bash
bundle exec ../ruby/ruby /usr/bin/irb
```
since the `which irb` now points to bash script that obviously can't be interpreted by ruby.

**Comment by ioquatix** [comment]
I'm having the same/similar problem.

**Comment by ioquatix** [comment]
From what I've read, it seems plausible that DYLD_LIBRARY_PATH no longer works with SIP which is on by default. Therefore, the only solution AFAIK is to specify the full path of the library or install it into a standard location.

**Comment by ioquatix** [comment]
Okay, by specifying explicit paths to ffi_lib for `glib-2.0`, `gobject-2.0` and `vips` to `/opt/local/lib/libX.dylib` it worked. So, it's clearly a search path issue, but it was working before upgrading to high Sierra.

**Comment by Nakilon** [comment]
@ioquatix with what Ruby distribution did it work for you? System one, or rbenv, or rvm?

**Comment by ioquatix** [comment]
I'm using `rvm`.

**Comment by jcupitt** [comment]
The ruby-ffi issue on this has an interesting idea:

https://github.com/ffi/ffi/issues/461

They are suggesting that when SIP is on, executables started from `/usr/lib` automatically have all environment variables stripped. This means `DYLD_*` is removed, and so ffi can't find the library.

To fix this, simple make a link from `/usr/bin/ruby` to `/usr/local/bin/ruby`:

```
ln -s /usr/bin/ruby /usr/local/bin/ruby
```

and it might all start working. Worth a try.

**Comment by Nakilon** [comment]
Doesn't work for `rspec` because:
```bash
$ head -1 `which rspec`
#!/usr/bin/env ruby
```

**Comment by Nakilon** [comment]
Upgraded macOS from El Captain to High Sierra -- it comes with Ruby 2.3.3. And issue seems to be gone.

**Comment by caioabe** [comment]
This worked for me:
Macos M1
Rbenv
Ruby 3.0.1
Rails 7.0.1

Just ran `arch -x86_64 brew install vips` and the action_text successfully printed my jpg in trix editor content.
