### ISSUE TITLE
How to set concurrency and SIMD for Vips?

### ISSUE THREAD

**Issue by hmistry** [jcupitt/ruby-vips#142]
How do I check settings for concurrency and SIMD?

How do I set the concurrency and SIMD?

The javascript Vips library, Sharp, allows this - I'd like to do same in ruby-vips, see:
http://sharp.dimens.io/en/stable/api-utility/#concurrency
http://sharp.dimens.io/en/stable/api-utility/#simd

**Comment by jcupitt** [comment]
You can set environment variables before `require "vips"`, perhaps:

```ruby
ENV["VIPS_CONCURRENCY"] = "1"
ENV["VIPS_NOVECTOR"] = "1"
require 'vips'
```

But you're right, there should be proper controls. I've just opened an issue for putting them in.

**Comment by jcupitt** [comment]
I'll close, let's do the two together on #143.

**Comment by hmistry** [comment]
@jcupitt Thanks for the quick response and patch! 

I tried using the ENV approach but neither SIMD nor concurrency seem to affect the time take by Vips to resize the image. Does that make sense to you? 

Using: `Vips::Image.thumbnail(ORIGINAL, width).write_to_file(name)`
Image is 5.1MB jpg, 4160x3120, being resized to 800x800, 500x500, and 300x300.

**Comment by jcupitt** [comment]
Hello, I made a test program:

```ruby
ENV["VIPS_CONCURRENCY"] = "1"
ENV["VIPS_NOVECTOR"] = "1"

require "vips"

Vips::Image.thumbnail(ARGV[0], 800).write_to_file("8.jpg")
Vips::Image.thumbnail(ARGV[0], 500).write_to_file("5.jpg")
Vips::Image.thumbnail(ARGV[0], 300).write_to_file("3.jpg")
```

Then ran like this:

```
john@kiwi:~/try$ vipsheader x.jpg 
x.jpg: 4160x3120 uchar, 3 bands, srgb, jpegload
john@kiwi:~/try$ time ruby thumb.rb x.jpg

real	0m0.417s
user	0m0.396s
sys	0m0.028s
john@kiwi:~/try$ time ruby thumb.rb x.jpg

real	0m0.426s
user	0m0.408s
sys	0m0.028s
john@kiwi:~/try$ time ruby thumb.rb x.jpg

real	0m0.419s
user	0m0.408s
sys	0m0.020s
```

You can see that real (wall clock) time is always higher than CPU time, ie. there's no parallelism.

If I comment out the ENV lines and try again I see:

```
john@kiwi:~/try$ time ruby thumb.rb x.jpg

real	0m0.391s
user	0m0.432s
sys	0m0.028s
john@kiwi:~/try$ time ruby thumb.rb x.jpg

real	0m0.416s
user	0m0.452s
sys	0m0.036s
john@kiwi:~/try$ time ruby thumb.rb x.jpg

real	0m0.413s
user	0m0.460s
sys	0m0.040s
```

Now wall clock time is always less than CPU time, ie. there is parallelism. 

The differences are small, because thumbnailing JPEG images is very simple. libjpeg supports shrink-on-load: when you load a JPEG image you can ask for 1:1, 1:2, 1:4 or 1:8 size reduction. `thumbnail` is looking at the target size, picking a libjpeg reduction to

**Comment by jcupitt** [comment]
Sorry, pressed comment by mistake, stupid touchpad. I've updated it now.

**Comment by hmistry** [comment]
Thanks a lot for the explanation - is very helpful.
