### ISSUE TITLE
Any way to get header information?

### ISSUE THREAD

**Issue by tozz** [jcupitt/ruby-vips#145]
First off, thanks for the great work with vips, swapped out my GraphicsMagick implementation and it's faster and probably more secure :)

The only thing I'm missing is getting the header data, I've searched through the documentation but can't find anything that seem to give me what `vipsheader -a file.jpg` does, am I missing something or is this not possible with ruby-vips?

**Comment by jcupitt** [comment]
Hello, I'm glad it's working for you. You need `get_fields`:

```ruby
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.new_from_file "k2.jpg"
=> #<Image 1450x2048 uchar, 3 bands, srgb>
irb(main):003:0> x.get_fields
=> ["width", "height", "bands", "format", "coding", "interpretation", "xoffset", "yoffset", "xres", "yres", "filename", "vips-loader", "jpeg-multiscan", "exif-data", "resolution-unit", "exif-ifd0-Orientation", "exif-ifd0-XResolution", "exif-ifd0-YResolution", "exif-ifd0-ResolutionUnit", "exif-ifd2-ExifVersion", "exif-ifd2-FlashPixVersion", "exif-ifd2-ColorSpace", "exif-ifd2-PixelXDimension", "exif-ifd2-PixelYDimension", "orientation", "vips-sequential"]
irb(main):004:0> x.get "exif-ifd2-ColorSpace"
=> "65535 (Internal error (unknown value 65535), Short, 1 components, 2 bytes)"
```

It was added in libvips 8.5, so you'll need to have that installed for ruby-vips to pick it up.

**Comment by tozz** [comment]
Ah, it was that simple :) Thanks for the quick reply!
