### ISSUE TITLE
Question about color spaces and ICC profiles

### ISSUE THREAD

**Issue by tozz** [jcupitt/ruby-vips#146]
Three questions really;
It seems vips always convert images to sRGB?
I have a JPEG with the AdobeRGB color space ICC embedded.
`image.get "interpretation"` returns `:srgb` and saving the image keeps the ICC, but if the colors were converted to sRGB this wouldn't work?
I'm probably missing something, how would I know what color space the image is in if ruby-vips always returns `:srgb`, save for parsing the ICC data manually?

Edit:
Using `image.icc_import embedded: true` gives me LAB.

**Comment by jcupitt** [comment]
Hello, there's an intro to how libvips handles colour in the "colour" section:

http://jcupitt.github.io/libvips/API/current/libvips-colour.html#libvips-colour.description

Mostly you don't need to think about it, unless you want to discover or change the colourspace.

When you load an image from a jpeg (for example), `interpretation` will be set to sRGB, though really the jpeg loader has no idea what RGB the jpeg is really using. The pixel values in the image will be exactly those stored in the file, and the profile will be carried over. This means that, for example:

```
vips invert x.jpg y.jpg
vipsthumbnail x.jpg
```

Will work whatever RGB the image is using.

If you want to change the colourspace, your source image must be tagged with an ICC profile, or you must supply the correct profile somehow. You can then:

* Use the embedded or external ICC profile to import the image to PCS (profile connection space), which is XYZ or LAB
* From PCS, you can write directly to sRGB, or if you have a profile, you can export to that device space with the profile
* You can transform directly between device spaces if you have a pair of profiles
* You can also use sRGB as something like PCS: if an image is in sRGB, you can directly convert to LAB (for example) without needing a profile

To discover the colourspace of an image, you need to check for the presence of an ICC profile: if there's no profile, you can assume sRGB (though you'll need to consider CMYK, or perhaps RGBA in the case of PNG). If there is a profile, you'll need to extract it and use an ICC lib to identify the colourspace.

**Comment by tozz** [comment]
Alright, that makes sense, I did read the color section but got confused because it only mentioned sRGB and not image color space in general.
This explanation is actually a lot more understandable than the documentation page, maybe something to incorporate?

Thanks for the quick and detailed reply!
