### ISSUE TITLE
draw_point isn't implemented yet?

### ISSUE THREAD

**Issue by Nakilon** [jcupitt/ruby-vips#148]
http://jcupitt.github.io/libvips/API/8.6/libvips-draw.html#vips-draw-point

**Comment by jcupitt** [comment]
Hello, it's just a convenience function in the C API, it's defined as `draw_rect x, y, 1, 1`. 

You're right that there should be a matching convenience function in Ruby.

**Comment by jcupitt** [comment]
I added `draw_point`. 

This needs to be thought about with the destructive issue:

https://github.com/jcupitt/ruby-vips/issues/139

**Comment by jcupitt** [comment]
See https://github.com/libvips/ruby-vips/issues/139

**Comment by Nakilon** [comment]
This file is missing the `draw_point` and `draw_point!` does not seem to be available.

**Comment by jcupitt** [comment]
You're right, we need `draw_point!` as well, I'd forgotten about this.

Plain `draw_point` seems to work. I tried:

```
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.black(3,3)
=> #<Image 3x3 uchar, 1 bands, multiband>
irb(main):003:0> x = x.draw_point(255, 1, 1)
=> #<Image 3x3 uchar, 1 bands, multiband>
irb(main):004:0> x.write_to_file("x.png")
=> nil
irb(main):005:0> 
```

And I get the expected image.

**Comment by jcupitt** [comment]
I added a `draw_point!` method. Thanks for reporting this!
