### ISSUE TITLE
Any way to constrain width, but not height?

### ISSUE THREAD

**Issue by kaspergrubbe** [jcupitt/ruby-vips#150]
Hi!

Is it possible to thumbnail or scale images with the `--size` argument described here

https://jcupitt.github.io/libvips/API/current/Using-vipsthumbnail.md.html 

and here 

https://github.com/jcupitt/libvips/issues/781 ?

Right now I am seeing something strange with the `#thumbnail`-method. Basically I have a `600x647` image that I want to scale down to a width of `100` (I do not care about height).

```ruby
image = Vips::Image.new_from_file(stored_image.file.path)
=> #<Image 600x647 uchar, 4 bands, srgb>

image = image.thumbnail_image(100)
VIPS-INFO: selected loader is image source
VIPS-INFO: input size is 600 x 647
VIPS-INFO: converting to processing space srgb
VIPS-INFO: premultiplying alpha
VIPS-INFO: shrinkv by 3
VIPS-INFO: shrinkh by 3
VIPS-INFO: residual reducev by 0.463679
VIPS-INFO: reducev: 14 point mask
VIPS-INFO: residual reduceh by 0.463679
VIPS-INFO: reduceh: 14 point mask
VIPS-INFO: unpremultiplying alpha
=> #<Image 93x100 uchar, 4 bands, srgb>

image = image.thumbnail_image(100, height: 108)
VIPS-INFO: selected loader is image source
VIPS-INFO: input size is 93 x 100
VIPS-INFO: converting to processing space srgb
VIPS-INFO: premultiplying alpha
VIPS-INFO: residual scale 1.07527 x 1.07527
VIPS-INFO: unpremultiplying alpha
=> #<Image 100x108 uchar, 4 bands, srgb>
```

I think I understand the reason why `#thumbnail_image(100)` does not have a width of 100, and it is because it is interpreted as a box of `100x100`, and then Vips will try to satisfy that.

So I guess what I want is to pass `100x` (as discussed in the Github issue), but is there any way to achieve that?

**Comment by jcupitt** [comment]
Hello @kaspergrubbe, just give a large number for height (10000000?) and the image will be resized to fit within a 100x10000000 box. That's what `vipsthumbnail` does. 

It does feel a bit ugly. There's an issue to use an extra flag for this somewhere.

**Comment by kaspergrubbe** [comment]
Wow, thanks for your fast response, yes, that does indeed work and all my tests are green again (converting from GraphicsMagick).

**Comment by jcupitt** [comment]
I'm glad your tests are green!

**Comment by kaspergrubbe** [comment]
I guess the issue with the extra flag you mentioned is this: https://github.com/jcupitt/libvips/issues/709 (so I will just reference it here)
