### ISSUE TITLE
Unable to call dzsave: wrong number of arguments

### ISSUE THREAD

**Issue by sickrandir** [jcupitt/ruby-vips#153]
Recently I upgraded libvips to 8.6.2 and ruby-vips to 2.0.9.
My scripts for generating image pyramids unfortunately stopped to work and the error I get is simply:
Vips::Error: unable to call dzsave: you supplied 3 arguments, but operation needs 2
However it should still work as I'm calling dzsave simply like this:
`image.dzsave('/home/user/test', options)`
If I call it like this, it works:
`image.dzsave('/home/user/test')`

but I need to supply the 'options' argument.
Is it still supposed to work like it used to or am I missing something?

Thanx

**Comment by jcupitt** [comment]
Hello @sickrandir, there were some very minor changes, and ruby-vips now supports named parameters, but it should still work. I made an example:

```ruby
require 'vips'

im = Vips::Image.new_from_file ARGV[0]

puts "saving to x1 .."
im.dzsave "x"

puts "saving to x2 with an option .."
im.dzsave "x2", overlap: 2

puts "saving to x3 with a hash of options .."
options = {overlap: 2}
im.dzsave "x3", options
```

What code is failing for you, and what was the previous version you used?

**Comment by sickrandir** [comment]
Thanks for the fast answer! Using your code I realized that the problem could be in the ruby upgrade that I also did (2.2.3 to 2.3.6), not in ruby-vips.
My code was quite old and I defined the opts hash the old ruby way:
`opts = { "overlap" => 2, "tile_size" => 512}`
If I define it like this:
`opts = {overlap: 2, tile_size: 512}`
the line of code:
`image.dzsave '/home/user/test', opts`

starts to work again!

Thanx

**Comment by jcupitt** [comment]
Huh strange, this works for me:

```ruby
require 'vips'

im = Vips::Image.new_from_file ARGV[0]

puts "saving to x1 .."
im.dzsave "x"

puts "saving to x2 with an option .."
im.dzsave "x2", overlap: 2, tile_size: 512

puts "saving to x3 with a hash of options .."
options = {overlap: 2, tile_size: 512}
im.dzsave "x3", options

puts "saving to x4 with an old-style hash of options .."
options = {:overlap => 2, :tile_size => 512}
im.dzsave "x4", options
```

With ruby 2.3.3.

**Comment by sickrandir** [comment]
Sorry for not answering for so long. The code you posted worked also for me. It's the version with strings as keys that does't work anymore for me:
{ "overlap" => 2, "tile_size" => 512}
I changed the definition and all it's working.
Thanx

**Comment by jcupitt** [comment]
Ah, I see! Yes, that makes sense, I should have thought of it. Yes, Symbols are required now, I think.
