### ISSUE TITLE
Am I missing smth or is documentation not telling us that `rot(1)` is rather `rot(:d90)` than rotate by 1 radian?

### ISSUE THREAD

**Issue by Nakilon** [jcupitt/ruby-vips#157]

**Comment by jcupitt** [comment]
Hello @Nakilon, yes, `rot()` rotates by 0/90/180/270 degrees with an enum, so `rot(1)` is `rot(:d90)`.

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-rot

**Comment by Nakilon** [comment]
OK, I see the mention of `enum` and `#similarity` method in these docs but not in Ruby docs.  
Does `#similarity` rotate by arbitrary angle? Then this method would be more obvious to have the name `#rotate`.

**Comment by jcupitt** [comment]
The ruby docs are mostly autogenerated, so they don't have all the detail. The C docs are supposed to be the definitive source.

The name `rot` was picked for the fixed angle rotates about 25 years ago :( You're right, `rotate` is unused at the moment, perhaps this should be a synonym for `similarity`.

**Comment by jcupitt** [comment]
... it would be possible to improve the Ruby autodocs quite a bit. GObject-introspection creates a huge XML file with all of the extracted doc comments and stuff from run-time introspection. For example (from Vips-8.0.gir):

```
      <method name="rot" c:identifier="vips_rot" introspectable="0">
        <doc xml:space="preserve">Rotate @in by a multiple of 90 degrees.

Use vips_similarity() to rotate by an arbitary angle. vips_rot45() is
useful for rotating convolution masks by 45 degrees.

See also: vips_flip(), vips_similarity(), vips_rot45().</doc>
        <return-value transfer-ownership="none">
          <doc xml:space="preserve">0 on success, -1 on error</doc>
          <type name="gint" c:type="int"/>
        </return-value>
        <parameters>
          <instance-parameter name="in" transfer-ownership="none">
            <doc xml:space="preserve">input image</doc>
            <type name="Image" c:type="VipsImage*"/>
          </instance-parameter>
          <parameter name="out"
                     direction="out"
                     caller-allocates="0"
                     transfer-ownership="full">
            <doc xml:space="preserve">output image</doc>
            <type name="Image" c:type="VipsImage**"/>
          </parameter>
          <parameter name="angle" transfer-ownership="none">
            <doc xml:space="preserve">rotation angle</doc>
            <type name="Angle" c:type="VipsAngle"/>
          </parameter>
          <parameter name="..." transfer-ownership="none">
            <doc xml:space="preserve">%NULL-terminated list of optional named arguments</doc>
            <varargs/>
          </parameter>
        </parameters>
      </method>
```

So you could write a little Ruby to walk that and spit out Yard docs.

**Comment by jcupitt** [comment]
I just added `rotate` to git master, so this should be in 8.7.

Thanks for the suggestion!
