### ISSUE TITLE
Vips::Error: composite: there must be X blend modes

### ISSUE THREAD

**Issue by sickrandir** [jcupitt/ruby-vips#158]
I have a strange problem with ruby-vips on my mac.
If I execute the same piece of code in the ruby shell it works but in the rails console it throws an error.
For testing purposes I just made five copies of the same image and I try to use composite like this:

`path = '/path/to/files/prod'`
`(1..5).each do |i|`
`	imgs.push(Vips::Image.new_from_file path+i.to_s+'.jpg') `
`end`
`res = Vips::Image.composite(imgs,2)`

in the rails console I get:

> Vips::Error: composite: for 5 input images there must be 4 blend modes

I just can't figure out why it should behave differently in the rails console.

**Comment by jcupitt** [comment]
Could they be picking up different version of the gem? Maybe try uninstall all ruby-vipes you can find, then just reinstalling the latest.

It used to insist you gave it N-1 blend modes even if they were all the same. Only the latest version lets you specify a single mode for all the blends.

**Comment by sickrandir** [comment]
Yes, that was it... now that I rebooted the Ruby shell and the Rails console are both picking up version 8.6.2 and it's working as expected. Thanx
