### ISSUE TITLE
Error when writing destination doesn't have extension

### ISSUE THREAD

**Issue by janko-m** [jcupitt/ruby-vips#160]
First of all, thank you very much for creating maintaining VIPS ❤️

I noticed that if I try to write a `Vips::Image` to a path which doesn't have an extension, ruby-vips throws an error

```rb
require "vips"
require "tempfile"

vips_image = Vips::Image.new_from_file("test/fixtures/portrait.jpg")
vips_image.write_to_file(Tempfile.new.path)
```
```
No known saver for '/var/folders/k7/6zx6dx6x7ys3rv3srh0nyfj00000gn/T/20180311-51784-139sd50'. (Vips::Error)
```

I presume this is because ruby-vips doesn't know in which format should the file be saved. Could ruby-vips in this case perhaps save the result in the same format as the input file?

**Comment by jcupitt** [comment]
That's right, `write_to_file` picks the saver from the file extension. 

You can pick a particular saver yourself, for example:

```ruby
vips_image.jpegsave Tempfile.new.path
```

Would that solve your problem?

**Comment by janko-m** [comment]
@jcupitt Well, the thing is that I don't know which type the input file is (JPEG, PNG etc), I'm writing generic logic for all common image types.

I was wondering if ruby-vips possibly already knows which type of file it is (I'm assuming it has to, in order to be able to know on `new_from_file` whether to call `jpegload`, `pngload` etc.), then perhaps ruby-vips could automatically choose the correct saver in case the destination path doesn't have an extension.

Or is there some VIPS function to tell which type the file is?

**Comment by jcupitt** [comment]
Hello again @janko-m, 

It records the thing that originally loaded the file, so you could pick a saver from that:

```
john@kiwi:~$ cd pics
john@kiwi:~/pics$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> a = Vips::Image.new_from_file "k2.jpg"
=> #<Image 1450x2048 uchar, 3 bands, srgb>
irb(main):003:0> a.get "vips-loader"
=> "jpegload"
```

But that won't always help. GIFs, for example, can be loaded by `gifload` or `magickload`, depending on how your libvips has been configured, and an SVG file doesn't really have a saver once it has been rasterized. A Q90 JPG won't look the same as a Q50 JPG. What if someone uploads an interlaced PNG? You wouldn't want to save that as an interlaced PNG, it would cause severe performance problems. 

I think if you want to copy a file, you should probably use the system copy function. If you want to resize (for example), then I'd just always use JPG.

**Comment by janko-m** [comment]
> But that won't always help. GIFs, for example, can be loaded by gifload or magickload, depending on how your libvips has been configured, and an SVG file doesn't really have a saver once it has been rasterized. A Q90 JPG won't look the same as a Q50 JPG. What if someone uploads an interlaced PNG? You wouldn't want to save that as an interlaced PNG, it would cause severe performance problems.

Thanks for the explanation, that makes sense 👍 

>  If you want to resize (for example), then I'd just always use JPG.

Ok, choosing JPEG as the default format when the file type is not known is a good option 👍. Thanks for your input!
