### ISSUE TITLE
Best way to check whether an image is corrupted?

### ISSUE THREAD

**Issue by janko-m** [jcupitt/ruby-vips#166]
I would like users of the `image_processing` gem to be able to validate whether the user-uploaded images are not corrupted, before accepting them an processing them. So I'm searching for the best way to validate the images. This is what I currently have:

```rb
def valid_image?(file)
  image = ::Vips::Image.new_from_file(file.path, fail: true)
  format = File.extname(file.path)[1..-1] || "jpg"
  image.write_to_buffer(".#{format}").clear
  true
rescue Vips::Error
  false
end
```

I like this solution, but the only downside is that I'm loading the whole image into memory (though it's immediately deallocated with `String#clear`). The alternative is writing to a temporary file, which makes the code a bit more complex because I have to erase the file afterwards.

```rb
def valid_image?(file)
  image = ::Vips::Image.new_from_file(file.path, fail: true)
  format = File.extname(file.path)[1..-1] || "jpg"
  output = Tempfile.new(["null", ".#{format}"])
  image.write_to_file(output.path)
  true
rescue Vips::Error
  false
ensure
  output.close! if output
end
```

ImageMagick has a ["null" output format](http://www.imagemagick.org/Usage/files/#null), which just thows away the image results.

```
$ convert -regard-warnings input.jpg null:
```

I thought about just writing to `/dev/null`, but ruby-vips needs the output format to have an extension.

```rb
image.write_to_file(File::NULL)
# Vips::Error: No known saver for '/dev/null'
```

I just wanted to check if there was perhaps another way. But if not, feel free to close this, I'm ok implementing the temporary output file solution.

**Comment by janko-m** [comment]
Nevermind, I'm totally fine with a temporary file, I just remembered that there is a `Tempfile.create` which accepts a block and automatically deletes the file at the end of the block, so I can do:

```rb
def valid_image?(file)
  image = ::Vips::Image.new_from_file(file.path, fail: true)
  format = File.extname(file.path)[1..-1] || "jpg"
  Tempfile.create(["null", ".#{format}"]) { |tempfile| image.write_to_file(tempfile.path) }
  true
rescue Vips::Error
  false
end
```

**Comment by jcupitt** [comment]
You could calculate some stats, such as image average.

```ruby
image = Vips::Image.new_from_file filename, access: :sequential
average = image.avg
```

That will scan the whole file and throw an exception if there's a problem.

It will be horribly slow though. My preference would be to have this as an optional `validate` method, and by default just let processing fail later.

Did you see the "Opening files" chapter in the docs?

http://jcupitt.github.io/libvips/API/current/How-it-opens-files.md.html

It tries to run through how image files are opened and when memory is allocated and freed.

**Comment by janko-m** [comment]
@jcupitt Thanks a bunch, I tried this now and it's twice as fast as the previous solution! I just had to add `fail: true` to make it actually raise an exception. The chapter you linked is also very useful.

**Comment by janko-m** [comment]
> It will be horribly slow though. My preference would be to have this as an optional validate method, and by default just let processing fail later.

I agree it shouldn't be automatic, my `#valid_image?` method is something that users will have to explicitly call in their validation if they want to validate the image.

**Comment by Nakilon** [comment]
I used ImageMagick to check for corruption:
```ruby
system("identify", "-verbose", image_filename, out: IO::NULL, err: IO::NULL)
```
as was proposed here https://stackoverflow.com/a/39304913/322020

**Comment by janko-m** [comment]
@Nakilon Note that you also have to add `-regard-warnings` if you want the shell command to return a nonzero exit status. So it would be:

```rb
system("identify", "-regard-warnings", "-verbose", image_filename, out: IO::NULL, err: IO::NULL)
```

If you use MiniMagick, it will automatically raise a `MiniMagick::Error` with stderr in the message:

```rb
MiniMagick::Tool::Identify.new do |cmd|
  cmd.regard_warnings
  cmd.verbose
  cmd << image_filename
end # raises MiniMagick::Error in case of corrupt images
```

However, `identify -verbose` is terribly slow, it takes 2.6s for me on a 2.8MB image. But I recently discovered a faster way on the ImageMagick forums, which is to convert image and dump it to "null device".

```rb
MiniMagick::Tool::Convert do |cmd|
  cmd.regard_warnings
  cmd << image_filename
  cmd << "null:"
end
```

For a 2.8MB image this now takes only 0.26s, which is 10x faster than the `identify -verbose` version.

Anyway, that's not related to ruby-vips, I just wanted to mention it here.
