### ISSUE TITLE
How to call vips_addalpha()?

### ISSUE THREAD

**Issue by janko-m** [jcupitt/ruby-vips#168]
I noticed that libvips has the [`vips_addalpha()`](http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-addalpha) function for adding the alpha channel, but I'm not able to call it from ruby-vips and it's not listed in the RDocs.

```rb
require "vips"
image = Vips::Image.grey(16, 16)
image.addalpha
```
```
VipsOperation: class "addalpha" not found (Vips::Error)
```

I'm using the latest versions:

```
$ vips --version
vips-8.6.3-Thu Mar  8 15:18:35 UTC 2018
$ gem list ruby-vips
ruby-vips (2.0.9)
```

**Comment by jcupitt** [comment]
Hello again @janko-m,

Ruby-vips uses ffi and libvip's own run-time introspection rather than static analysis of source. To be callable from ruby, code has to be a subclass of `VipsOperation`.  

`hasalpha` / `addalpha` are tiny convenience functions for the C binding, so they would be best reimplemented in Ruby. Something like:

```ruby
def hasalpha?
    bands == 2 ||
    (bands == 4 && interpretation != :cmyk) ||
    bands > 4
end

def addalpha
    max_alpha = (interpretation == :grey16 || interpretation == :rgb16) ? 65535 : 255
    bandjoin(max_alpha)
end
```

**Comment by janko-m** [comment]
@jcupitt Thanks very much for the reply.

I see. Would it be worthwhile to make `vips_addalpha()` and/or `vips_hasalpha()` subclasses of `VipsOperation` in libvips?

My use case is that I would like to add alpha to an image if it doesn't already have one, for the [`#resize_and_pad`](https://github.com/janko-m/image_processing/blob/master/doc/vips.md#resize_and_pad) method, which resizes and image to specified dimensions maintaining aspect ratio, and fills the rest of the space with a background color. I would like users to be able to make this background color transparent regardless of whether the source image has an alpha channel or not (in which case it would allow the user to add the missing alpha channel if it doesn't exist already).

**Comment by jcupitt** [comment]
OK, 2.0.11 is up and has `#has_alpha?` and `#add_alpha` methods.

**Comment by janko-m** [comment]
Awesome, thanks @jcupitt and @aried3r!
