### ISSUE TITLE
problem setting up ruby-vips on centos 6.9

### ISSUE THREAD

**Issue by lsat12357** [jcupitt/ruby-vips#172]
It appears vips is working, and I believe I've found the relevant comments on setting things up as far as pkg-config and /etc/ld.so.conf, but something is missing?!

[root@f072481e1cd5 oregondigital]# vips -v
vips-8.6.3-Thu Mar  8 15:18:35 UTC 2018

[root@f072481e1cd5 vips-8.6.3]# ./vipsavg ./test/images/Landscape_6.jpg 
Hello World!
Pixel average of ./test/images/Landscape_6.jpg is 79.4338

[root@f072481e1cd5 vips-8.6.3]# echo $PKG_CONFIG_PATH
/usr/local/lib/pkgconfig

[root@f072481e1cd5 oregondigital]# pkg-config --list-all | grep -i vips
vips                                vips - Image processing library
vips-cpp                            vips-cpp - C++ API for vips8 image processing library
vipsCC                              vipsCC - deprecated C++ API for vips image processing library

[root@f072481e1cd5 oregondigital]# pkg-config vips --libs
-pthread -L/usr/local/lib -lvips -lgobject-2.0 -lgthread-2.0 -lrt -lglib-2.0  

[root@f072481e1cd5 oregondigital]# ruby -v
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]

[root@f072481e1cd5 oregondigital]# gem list
...
ffi (1.9.0)
...
rails (4.2.7.1)
...
ruby-vips (2.0.10)

[root@f072481e1cd5 oregondigital]# ruby -e "require 'vips'"

(process:1441): GLib-CRITICAL **: g_hash_table_lookup: assertion `hash_table != NULL' failed

(process:1441): GLib-CRITICAL **: g_hash_table_lookup: assertion `hash_table != NULL' failed

(process:1441): GLib-CRITICAL **: g_hash_table_lookup: assertion `hash_table != NULL' failed

(process:1441): GLib-CRITICAL **: g_hash_table_lookup: assertion `hash_table != NULL' failed

(process:1441): GLib-CRITICAL **: g_hash_table_lookup: assertion `hash_table != NULL' failed

(process:1441): GLib-CRITICAL **: g_hash_table_lookup: assertion `hash_table != NULL' failed

(process:1441): GLib-CRITICAL **: g_hash_table_lookup: assertion `hash_table != NULL' failed

(process:1441): GLib-CRITICAL **: g_hash_table_lookup: assertion `hash_table != NULL' failed

**Comment by jcupitt** [comment]
Hello @lsat12357,

ruby-vips-2.0 just uses FFI, there's no binary part, so you don't need to set up `PKG_CONFIG_PATH` any more. As long as it can find the `libvips.so` shared library, you should be OK.

Perhaps you have a couple of libvips-es installed and ruby is picking up the wrong one? Have you set `LD_LIBRARY_PATH`? Which ruby and libvips are you using?

I'll try to make an example in docker.

**Comment by jcupitt** [comment]
I see the error here too:

https://github.com/jcupitt/docker-builds/tree/master/ruby-vips-centos6

Perhaps the glib shipped with centos is too old? I'll experiment.

**Comment by jcupitt** [comment]
I think I've found it: on older glib, like the 2.28 that ships with CentOS6, you need to call `g_type_init()` explicitly. I've added this to ruby-vips and it now seems to work on docker for me.

Would you be able to test ruby-vips git master?

Thanks for reporting this bug!

**Comment by lsat12357** [comment]
thank you so much @jcupitt! I am not seeing those glib messages now. I am also using docker, to try to test this and other upgrades before we deploy them on production, so hopefully all goes well there too.

**Comment by jcupitt** [comment]
OK, 2.0.11 pushed with this fix. Thanks again!
