### ISSUE TITLE
Question : How to get a list of common colours from image? 

### ISSUE THREAD

**Issue by dkam** [jcupitt/ruby-vips#183]
I would like to generate list of the X most common colours from an image.  I assume there's a quantiser for reducing the number of colours?  Or should I loop through the results from image.getpoint and use something like k-mean clustering?

Edit - I just saw this https://github.com/jcupitt/libvips/issues/259 which might help me.

**Comment by jcupitt** [comment]
I meant to say, what's your ultimate aim? Perhaps there's another way to do what you want.

**Comment by jcupitt** [comment]
Ah OK. Yes, I think you'd need to use ffi to call something like libimagequant for the actual quantization. You could use libvips for the other image handling.

**Comment by jonian** [comment]
Hi @jcupitt, I'm trying to get the color palette of an image but I can't find an example on how to do it. What I have found is how to get the dominant color. Any help will be appreciated. Thanks!

```ruby
# From https://gist.github.com/jcupitt/bf233c9efabdb6483dea5c7243777258

im = Vips::Image.new_from_file(file, access: :sequential)

# 3D histogram ... make 10 x 10 x 10 bins, so 1000 possible colours
bins = 16
hist = im.hist_find_ndim(bins: bins)

# black is usually background or boring, so set that cell to 0 counts
# fetch (0, 0), set the 0th element of that to 0, paste back
pixel = hist.getpoint(0, 0)
pixel[0] = 0
pixel = Vips::Image.black(1, 1).add(pixel)
hist = hist.insert(pixel, 0, 0)

# (x, y) pixel with the most counts
v, x, y = hist.maxpos()
pixel = hist.getpoint(x, y)
z = pixel.find_index(v)

# convert indexes to rgb ... +0.5 to get the centre of each bin
r = (x + 0.5) * 256 / bins
g = (y + 0.5) * 256 / bins
b = (z + 0.5) * 256 / bins
```

**Comment by jcupitt** [comment]
Hi, libvips converts all palette (or indexed) images to RGB for precessing, so you can't really get the palette. 8.13 might add something like this for GIF sources, but that's all.

If you want to compute an optimised palette for an image, you'll need to use something like libimagequant.

**Comment by jonian** [comment]
Thank you for the quick response! I will take a look at libimagequant.
