### ISSUE TITLE
Travis builds both on 1.9.3 and ruby-head occasionally produce segmentation fault bug. 

### ISSUE THREAD

**Issue by stanislaw** [jcupitt/ruby-vips#32]
https://travis-ci.org/jcupitt/ruby-vips/jobs/5120262

...
939 /home/travis/build/jcupitt/ruby-vips/spec/vips/freq_filt_spec.rb:155: [BUG] Segmentation fault
940 ruby 1.9.3p327 (2012-11-10 revision 37606) [i686-linux]
...
```

**Comment by jcupitt** [comment]
I'll close, I think this has vanished.
