### ISSUE TITLE
tuning resamplers

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/ruby-vips#39]
Running into a small problem with very small images (150x150 or less). It's very slight but it has come up with some of the co-workers. 

Here's our current system:

![pix150](https://f.cloud.github.com/assets/47749/657160/0b463cd8-d544-11e2-9d8f-1a6d287c4dbb.jpeg)

and here's the new vips one:

![vips150](https://f.cloud.github.com/assets/47749/657161/14cdc294-d544-11e2-983f-24f72ae5f562.jpeg)

The areas of concern have been around the bowl of nuts and the top of the jar. Seem a little more artifacty? I think some of this is that our current system errors on the side of soft. I spent some time trying to apply very, very slight blurs and then blending them (couldn't find a good way to do image blending) to soften up edges. Even tried doing it using and edge detection mask, bluring, and applying it (that got weird, I think I did it wrong). 

Starting to wonder if I'm just running into the limits of the interpolators. Would my best approach here be looking into submitting a patch in libvips itself for the interpolators we use now? Or is there some approaches that I'm missing?

Finally - is there a good introductory text for this sort of stuff? I find it wildly interesting but I'm constantly bumping into the extents of my knowledge and it seems hard to find helpful info (other than constantly submitting GitHub issues :P ). 

Thanks once again, and hope you have a great weekend!

**Comment by jcupitt** [comment]
The vips resizing stuff has been reworked and should now be equivalent to GM. This new `vips_resize()` operation ought to be exposed in ruby-vips, I'll add a note to the TODO.

**Comment by bnferguson** [comment]
@jcupitt - That is awesome! Even though I've been away from the project I needed this for for a couple years now it's still been on my mind considering just how huge the jumps in performance were between VIPs and GM were at the time.

**Comment by jcupitt** [comment]
This should all be done now, I'll close.
