### ISSUE TITLE
Flatten support

### ISSUE THREAD

**Issue by harrisbaird** [jcupitt/ruby-vips#45]
Since 7.28.7, libvips has supported [flattening](https://github.com/jcupitt/libvips/blob/master/libvips/conversion/flatten.c) images, removing the alpha channel and replacing it with an optional background color.

Would it be for ruby-vips to support this?

**Comment by jcupitt** [comment]
ruby-vips has just been bumped to 1.0 and an API break. The new API supports flattening, so you should be OK.
