### ISSUE TITLE
dzsave support

### ISSUE THREAD

**Issue by noname00000123** [jcupitt/ruby-vips#54]
I understand libvips8 will automate integration of new and updated features, however advice on implementation or, better still, an example for dzsave within a rails app (using CarrierWave) would be greatly appreciated.

Or if not, flag it for addition to the CarrierWave-Vips gem.

**Comment by jcupitt** [comment]
There's an experimental ruby-vips8 binding with dzsave support here:

https://github.com/jcupitt/ruby-vips8

It has the serious problem that it must force a GC before each call to libvips :-( so still not quite production-ready.

**Comment by jcupitt** [comment]
ruby-vips has now been bumped to 1.0 and an API break. The new API supports dzsave, so you should be all set.
