### ISSUE TITLE
gem install/build fails with vips 7.40

### ISSUE THREAD

**Issue by troelskn** [jcupitt/ruby-vips#63]
I just installed libvips through homebrew, following the instructions here and got version `vips-7.40.11`. Next i ran `gem install ruby-vips` for version `0.3.9`, which fails with the following message:

    extconf.rb:27:in `<main>': no pkg_config for any of following libvips versions: 7.29, 7.28, 7.27, 7.26, 7.24, 7.23, 7.22, 7.20 (RuntimeError)

It would seem that ruby-vips doesn't know how to build against v. 7.40?

**Comment by skunkworker** [comment]
I also had this same problem and the fix by @troelskn worked, this should be added to the documentation.

**Comment by jcupitt** [comment]
I've updated the notes in the README, thanks for reporting this.

It's actually become simpler: with current homebrew and 7.42 there doesn't seem to be any need to mess with `PKG_CONFIG_PATH`, thank goodness.
