### ISSUE TITLE
Add webp support

### ISSUE THREAD

**Issue by sbalay** [jcupitt/ruby-vips#65]
Is there a chance to add to this gem support to webp image format?
libvips already has support for it.

**Comment by jcupitt** [comment]
If it's not too much work. I'll have a  look.

**Comment by tommasop** [comment]
+1

**Comment by jcupitt** [comment]
git master now has webp write.

I've updated the bundle and broken rspec support, this needs fixing.

Would webp read support be useful too?

Theres a new ruby binding here, if you've not seen it:

https://github.com/jcupitt/gir_ffi-vips

The new one is written in Ruby using gir_ffi and is quite a bit better. It has full webp support already, including write to and from memory buffers. It does leak slightly unfortunately, about 20 bytes per operation call.

**Comment by jcupitt** [comment]
There's a new version of ruby-vips with this feature in, I'll close. 

The current best vips8 Ruby binding is here:

https://github.com/jcupitt/ruby-vips8
