### ISSUE TITLE
(enh) JRuby / FFI support?

### ISSUE THREAD

**Issue by evadne** [jcupitt/ruby-vips#66]
Hi @jcupitt,

Are there plans to migrate the C parts in this Gem to a libFFI-compliant interface, so JRuby users can also enjoy the libvips binding?

If there’s no such a plan do you know whether this will be difficult to implement by somebody else? I am under the impression that everything under `ext` will need some level of attention.

Thanks
Eve

**Comment by jcupitt** [comment]
Hi Eve, you're in luck, I've done this already:

https://github.com/jcupitt/gir_ffi-vips

It works well, but unfortunately it has some problems with reference counting so you get quite bad leaks. I've filed an issue with gir_ffi but it's not been fixed yet:

https://github.com/mvz/gir_ffi/issues/52

If someone could have a look into this, that would be great. It's outside my area really.

**Comment by evadne** [comment]
[“fixed in master”](https://github.com/mvz/gir_ffi/issues/52#issuecomment-98982506) with `gir_ffi`.

@jcupitt :ok_hand: :question:

**Comment by jcupitt** [comment]
Yes, most of the leaks are gone now. It now just leaks array constants, so something like:

```ruby
a += [1, 2, 3]
```

which adds 1 to the first band, 2 to the second and 3 to the third, will leak about 20 bytes each time it is called. There's an issue for this leak as well:

https://github.com/mvz/gir_ffi/issues/54

If you're OK with tiny leaks like this, gir_ffi-vips is ready for use. There's a small set of tests and they all now pass. The underlying library is tested by the Python binding, the gir_ffi-vips tests just exercise the Ruby interface.

**Comment by jcupitt** [comment]
I've updated the README in `gir_ffi-vips` with some notes about the current leak status.

**Comment by jcupitt** [comment]
There's another Ruby binding for vips8 here:

https://github.com/jcupitt/ruby-vips8

Which builds on ruby-gnome2.

**Comment by harukizaemon** [comment]
Is JRuby officially supported?

**Comment by jcupitt** [comment]
Probably not. The last time I tried, `gir_ffi` had changed some stuff and broken `gir_ffi-vips`. It might be working again now, you'd need to experiment.

The gem I'm supporting is still `ruby-vips`.

**Comment by jcupitt** [comment]
There's a new ruby-vips being discussed here:

https://github.com/jcupitt/ruby-vips/issues/115

This uses plain FFI to call directly into the libvips shared library, so there's no gobject-introspection. It should work on Windows and JRuby (though I've not tested it), and it ought to be API compatible with the current ruby-vips version. It's a bit quicker too, which is nice. 

It all seems to be documented and working, it just needs some testing.

**Comment by evadne** [comment]
Thank you. What we ended up doing was running a C program (loosely based on `vipsthumbnail`) as a child process of the JRuby application (and it gives us ability to respawn child process if it goes over certain resource limits).

With a move back to FFI we will lose the safety factor so probably unlikely to change now. :/
