### ISSUE TITLE
Change documentation for vips7.

### ISSUE THREAD

**Issue by skunkworker** [jcupitt/ruby-vips#68]
Hi @jcupitt I added vips7 as its own formula now that homebrew/science moved on to vips8 already. It might be good to change the documentation on the readme to use the new formula instead.

**Comment by jcupitt** [comment]
Hi @skunkworker, are you seeing compatibility problems? vips is supposed to support both the vips7 and vips8 APIs, it's a bug if it isn't.

**Comment by skunkworker** [comment]
It turns out it was a mismanagement error, and theres no problem using just vips8 now.

**Comment by jcupitt** [comment]
Ah, glad it's working. I'll close.
