### ISSUE TITLE
Discover and extract pyramid tiff levels and tiles?

### ISSUE THREAD

**Issue by jpstroop** [jcupitt/ruby-vips#70]
So far I've figured out that I can do:

```
2.2.1 :002 > im = VIPS::TIFFReader.new('./color_pyramid.tif')
 => #<VIPS::TIFFReader:0x00000001d6f3c0 @page_number=nil, @sequential=false, @path="./color_pyramid.tif", @_im=nil> 
2.2.1 :003 > im.x_size
 => 1200 
2.2.1 :004 > im.page_number=1
 => 1 
2.2.1 :005 > im.x_size
 => 600 
2.2.1 :006 > im.page_number=2
 => 2 
2.2.1 :007 > im.x_size
 => 300 
2.2.1 :008 > im.page_number=3
 => 3 
2.2.1 :009 > im.x_size
VIPS::Error: VIPS error: tiff2vips: TIFF does not contain page 3
```

Which at least seems like a ham-handed way to figure our how many resolutions are available (though, of course, pages may not be different resolutions). It seems like I should be able to find out that this is indeed a pyramid tiff and how many resolutions/scale factors are available without having to loop through 1..n until I get an exception. Additionally I'd like to:

 * Find out the size of the tiles within the image (I happen to know this image was encoded w/ 512x512 tiles)
 * Extract one of the lower resolutions
 * Extract a tile from one of the resolutions

and transcode either of the latter two to anther format and write it out.

Is this possible? Any clues would help. TIA!

**Comment by jcupitt** [comment]
Hi, vips does not attach all image metadata, so you can't read arbitrary tiff tags. You probably need a lower-level library for that, perhaps a direct wrapping of libtiff.

Are you sure you need the tile size? vips will let you read any area from a tiff and uses enough caching that it's very quick. For example:

```
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> im = VIPS::Image.new "wtc-pyr.tif"
=> #<VIPS::Image:0x000000020cfee8>
irb(main):004:0> patch = im.extract_area 10, 10, 100, 100
=> #<VIPS::Image:0x000000021a0610>
irb(main):005:0> patch.write "x.jpg"
=> #<VIPS::Writer:0x0000000208dac0>
irb(main):006:0> im = VIPS::Image.new "wtc-pyr.tif", page_number = 4
=> #<VIPS::Image:0x00000002085690>
irb(main):007:0> patch = im.extract_area 10, 10, 100, 100
=> #<VIPS::Image:0x00000002104fd0>
irb(main):008:0> patch.write "x.png"
=> #<VIPS::Writer:0x00000002007830>
```

The arguments to `extract_area` are left, top, width, height. 

tiff does not actually record the number of pages in a file, you have to keep asking for pages until you hit an error. vips could have a `n_pages` field, but all it would do internally would be to loop over all page numbers.

**Comment by jcupitt** [comment]
Ooops, sorry, I've spent too long in Python, ruby-vips does it like this:

```
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> reader = VIPS::TIFFReader.new "wtc-pyr.tif", :page_number => 4
=> #<VIPS::TIFFReader:0x00000001c471a0 @page_number=4, @sequential=false, @path="wtc-pyr.tif", @_im=nil>
irb(main):003:0> reader.x_size
=> 585
irb(main):004:0> im = reader.read
=> #<VIPS::Image:0x00000001d22ed0>
irb(main):005:0> patch = im.extract_area 10, 10, 100, 100
=> #<VIPS::Image:0x00000001c09760>
irb(main):006:0> patch.write "x.png"
=> #<VIPS::Writer:0x00000001c05b38>
```

ie. you use `read` to trigger the actual image read and get something you can work with.

**Comment by jcupitt** [comment]
ruby-vips8 has a much simpler way of handling this, but it's still not working properly, unfortunately.

**Comment by jpstroop** [comment]
OK, thanks for the help and info!

Just so you know this isn't an arbitrary exercise, my reason for asking is that I'm implementing the [IIIF Image API](http://iiif.io/api/image/2.0/), which includes a [service for providing just enough info](http://iiif.io/api/image/2.0/#image-information) for a client to know what it can access (either efficiently, or in some cases, at all) to drive a rich web-client. I've done a few implementations in the past, but never in Ruby, and I've never supported pyramid TIFF as a source format (I also prefer to avoid ImageMagick at all costs :wink: ). Looking at the TIFF 6.0 spec w/ fresh eyes this morning, it doesn't look like it would be terribly difficult to extract what I need from the file (given some quiet time).

Closing--thanks again!

**Comment by jcupitt** [comment]
Oh OK, sounds fun. I guess you know about iipimage? They support IIIF, I think:

**Comment by jpstroop** [comment]
Yeah, Ruven was one of the first few adopters and has come to a few of our meetings. I'm also the dev/maintainer of [Loris](https://github.com/loris-imageserver/loris/), which was more or less the first.

**Comment by jcupitt** [comment]
I did a tiny tile server in C, it might be relevant:

https://github.com/jcupitt/tilesrv

That's for serving tiles from openslide images to a deepzoom viewer.
