### ISSUE TITLE
Files without extensions are not found

### ISSUE THREAD

**Issue by barrkel** [jcupitt/ruby-vips#71]
I tried to load a file:

    $ cp test.jpg /tmp/foo
    $ pry
    > require 'vips'
    > im = VIPS::Image.jpeg('/tmp/foo')
    VIPS::Error: VIPS error: VipsFormat: file "/tmp/foo:1,," not found
    from .../ruby-2.0.0-p353/gems/ruby-vips-0.3.9/lib/vips/reader.rb:45:in `read_internal'

**Comment by jcupitt** [comment]
Hi @barrkel , it depends on the vips library version, there have been some problems with vips7 filename parsing unfortunately. 

It works at least with the current stable version:

```
$ cp k2.jpg x
$ irb irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> im = VIPS::Image.new 'x'
=> #<VIPS::Image:0x007f804c1a1b38>
irb(main):003:0> im.x_size
=> 1450
```

You can use `.jpeg`, or if you use `.new` it'll sniff the file type from the first few bytes. Which libvips are you using?

**Comment by jcupitt** [comment]
I'll close, I think this is resolved.
