### ISSUE TITLE
Unfork

### ISSUE THREAD

**Issue by sandstrom** [jcupitt/ruby-vips#72]
Since this is the canonical ruby-vips repository, this would be more obvious if the repo was 'unforked' from `ender672` (having the text "forked from ender672/ruby-vips" removed).

The process is to simply send a message to https://github.com/contact and explain that you'd like to have it 'unforked' (mentioning that this is the new canonical repo should suffice).

Btw, I'm a big fan of ruby vips! :boat:

**Comment by jcupitt** [comment]
Hi @sandstrom, OK, I've sent in a request. Thanks for suggesting this!

**Comment by sandstrom** [comment]
@jcupitt Awesome! :smile:
