### ISSUE TITLE
fix travis

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/ruby-vips#75]
Travis has been disabled for now. It should be turned back on.

The difficulty is that ruby-vips now needs vips-8.2 or later, which is not widely available, and certainly not on travis. We need to build our own vips before testing ruby-vips.

There are some notes in the TODO, and stuff can be copy-pasted from the libvips `.travis.yml`.

**Comment by skunkworker** [comment]
@jcupitt I'm running into this issue in getting carrierwave-vips ported over to 8.2+.
For now would you recommend just downloading and building from scratch to get it testing or is there a distributed 8.2+ package that can be used?

**Comment by skunkworker** [comment]
Though it seems like from `https://launchpad.net/ubuntu/+source/vips` that the latest version for 12.04 LTS is `7.26.3-1build1`, which travis uses. Is that why it's not working yet?

**Comment by jcupitt** [comment]
Exactly, the ruby-vips `.travis.yml` needs to download and build its own libvips for testing. 

The php binding does this, it should be a simple copy-paste job:

https://github.com/jcupitt/php-vips/blob/master/.travis.yml

I've just been too lazy to actually do it.

**Comment by skunkworker** [comment]
@jcupitt so I tried modifying and adding travis back with a slightly modified php script. 
It builds successfully on 12.04 on Travis but after sudo make install it can't find the `.typelib` file.

https://travis-ci.org/consyse/ruby-vips/jobs/187093987

```/home/travis/.rvm/rubies/ruby-2.3.1/bin/ruby -I/home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib:/home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-support-3.5.0/lib /home/travis/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/exe/rspec spec/image_spec.rb spec/vips_spec.rb
Unable to load Vips
  Check that the vips library has been installed and is
  on your library path.
  Check that the typelib `Vips-8.0.typelib` has been 
  installed, and that it is on your GI_TYPELIB_PATH.
/home/travis/.rvm/gems/ruby-2.3.1/gems/gobject-introspection-3.0.8/lib/gobject-introspection/loader.rb:37:in `require': Typelib file for namespace 'Vips' (any version) not found (GLib::Error)
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/gobject-introspection-3.0.8/lib/gobject-introspection/loader.rb:37:in `load'
	from /home/travis/build/consyse/ruby-vips/lib/vips.rb:79:in `init'
	from /home/travis/build/consyse/ruby-vips/lib/vips.rb:47:in `const_missing'
	from /home/travis/build/consyse/ruby-vips/spec/image_spec.rb:7:in `<top (re```

**Comment by skunkworker** [comment]
What is the best way to get the `Vips-8.0.typelib` installed, I would've thought `sudo make install` would have done it.

**Comment by jcupitt** [comment]
Hi, my guess would be that it's not made the typelib because some part of gobject-intospection is missing. I might be able to have a look tomorrow.

**Comment by jcupitt** [comment]
Hi again, I copied your `.travis.yml`, made a couple of small changes, and it seems to be working! Branch here:

https://github.com/jcupitt/ruby-vips/tree/restore-travis

I added `libgirepository1.0-dev`, removed a few packages it doesn't need, and got it to install vips to `/usr` to avoid setting `GI_REPOSITORY_PATH`.

What do you think? I guess README needs a badge back.

**Comment by jcupitt** [comment]
... OK, badge in README.

**Comment by skunkworker** [comment]
Awesome. I knew it was something small that I was missing.

**Comment by jcupitt** [comment]
Merged to master. Thank you very much for your work on this issue @skunkworker!
