### ISSUE TITLE
Naming of gem.

### ISSUE THREAD

**Issue by ioquatix** [jcupitt/ruby-vips#77]
Calling gems "ruby-X" is a bit of an anti-pattern. Sure, the repo can be called ruby-vips or vips.rb or vips-rb, etc but the actual gem should be called just "vips" to match up with the name in "lib/vips".

**Comment by jcupitt** [comment]
I'm sure you're right, but I think it's too late to change now. 

I've reworded the description to make it seem a little less dumb: before the first sentence was `ruby-vips is a ruby extension for vips`, sigh.

**Comment by ioquatix** [comment]
It doesn't matter how you do it, you can easily leave the current release on ruby gems and do a new release it won't make a shred of difference, just update the docs and point to the new location, etc. People would understand why. But anyway, the ball is in your court on this one. Personally, I think it would be a good idea to claim "vips" before someone else does, if simply for that reason.

**Comment by ioquatix** [comment]
I'd also possibly suggest yanking `ruby-vips8` as it's confusing as hell right now for new users.

**Comment by sandstrom** [comment]
@ioquatix Though I agree with you, it's difficult to change a name when it's been used for a while.

Also, there was recently a repo name-change from `ruby-vips` -> `ruby-vips8` -> `ruby-vips` (back again). I'm super-happy @jcupitt was willing to make this change (revert to the old repo name).

See: https://github.com/jcupitt/ruby-vips8/issues/2

With a gem I guess one can publish them under two names, to avoid breaking anything

**Comment by ioquatix** [comment]
Sorry to bother you again with this. I've chosen to fork this gem and release it as just `vips`. I hope you don't see this as an asshole move, I'd be happy to relinquish control back to you if that's what you want.

Basically, we have problems deploying this gem to AWS, and we don't have much control over our environment (i.e. not possible to custom install code like libvips). So, I've opted to fork this gem, bundle in the source code for libvips, and build it on install. It's a good solution for us.

I hope you don't see this as me clobbering on your namespace. Perhaps one day we can merge the two.

I will do my best to make it very clear about the status of the fork and why it exists, as to avoid any kind of confusion.

https://github.com/ioquatix/vips

**Comment by ioquatix** [comment]
One other interesting thing which I didn't consider, is that now it's all part of one gem (excepting glib) it's much easier for upstream tests to use/cache. It's certainly going to be easier for us.

**Comment by jcupitt** [comment]
Oh no problem, do as you please. I'm not the original author anyway, I forked ruby-vips from Tim Elliot back in 2010 (where the name came from).

https://github.com/ender672/ruby-vips

Do you need to fork the entire thing? Could you make a tiny gem (called vips) which pulled in this ruby-vips and built/downloaded the library binary if necessary?

**Comment by jcupitt** [comment]
... I was just thinking that not forking the whole thing would ease maintenance.

**Comment by ioquatix** [comment]
I did start hacking it as you suggested but I needed to modify the FFI config in ‘vips.rb’ in the end it was just easier to fork but I will try to keep it up to date with your code.

**Comment by sandstrom** [comment]
@ioquatix perhaps some minor modifications to FFI config in upstream `ruby-vips` could make it possible for you to wrap it and only add the `libvips` + compile stuff into your `vips` gem?

**Comment by jcupitt** [comment]
Fair enough, I certainly understand the urgency.

Locating library binaries across platforms with ruby-ffi is a bit of a mess, especially on macOS. If you have any ideas for improving the situation, please do make a PR, I'd be delighted! 

A "true" solution would probably be a PR to ruby-ffi, because surely all ruby-ffi projects are facing this, but that might be harder to get accepted.

**Comment by Nakilon** [comment]
You don't have to push the fork to Rubygems to use it -- bundler can install from git repo.

**Comment by ioquatix** [comment]
Another gem depends on it to work

**Comment by Nakilon** [comment]
Oh, yes, gemspec can't depend on git repo. But you could specify repo in the main app Gemfile. That's not very nice and you would need to manually sync the ruby-vips version in Gemfiles of the main app and the Gemfile of the gem to be sure in their tests results, but it would work.
