### ISSUE TITLE
How to resize with 1.x release

### ISSUE THREAD

**Issue by ioquatix** [jcupitt/ruby-vips#78]
My existing resize code looks like

```
		def resize_to_fit(image, width, height, output_path)
			x_scale = Rational(width, image.width)
			y_scale = Rational(height, image.height)
			
			scale = [x_scale, y_scale].max
			
			if scale < 0.5
				shrink_factor = Rational(1, scale).floor
				shrink_factor -= 1 if shrink_factor == Rational(1, scale)
				
				image = image.shrink(shrink_factor)
				
				#puts "resize_to_fit(#{image}, #{width}, #{height}, #{output_path})"
				#puts "image #{image.width} #{image.height}"
				return resize_to_fit(image, width, height, output_path)
			elsif scale > 1.0
				# Just crop it.. no scale.
				width = image.width if x_scale > 1.0
				height = image.height if y_scale > 1.0
				
				scale = 1.0
			elsif scale == 1.0
				# nothing to do
			else
				image = image.affinei_resize(:bicubic, scale)
			end
			
			left = (image.width - width) / 2.0
			top = (image.height - height) / 2.0
			
			#puts "image.width #{image.width} image.height: #{image.height}"
			#puts "Left: #{left} Top: #{top} X: #{width} Y: #{height}"
			image = image.extract_area(left, top, width, height)
			
			#puts "image.width #{image.width} image.height: #{image.height} => #{output_path}"
			
			image = image.conv(self.class.convolution_mask)
			
			writer = Vips::JPEGWriter.new(image, quality: 85)
			writer.write_to_file(output_path)
		end
```

Can you suggest what to replace `shrink` (needs more arguments) and `image.affinei_resize` (gone)? Also, is this still the best way? I noticed there was custom interpolators. Should I just use those?

**Comment by ioquatix** [comment]
have some issues getting this to work... small repro:

```
> image.resize(1, interpolate: Vips::Interpolate.new(:bicubic))
Vips::Error: No such option 'interpolate',
from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/ruby-vips-1.0.2/lib/vips/call.rb:136:in `block in call_base_nogc'
```

Seems like can't specify interpolate option.. also tried string key:

```
> image.resize(1, 'interpolate' => Vips::Interpolate.new(:bicubic))
Vips::Error: No such option 'interpolate',
from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/ruby-vips-1.0.2/lib/vips/call.rb:136:in `block in call_base_nogc'
```

**Comment by jcupitt** [comment]
Hi @ioquatix, there's a new `resize` method which does a high-quality shrink for you in one go. It should be noticeably faster and better-quality than your current code.

Use it like:

```ruby
image = image.resize 0.2, :kernel => :cubic
```

Looking at the docs I see they've not been regenerated since the argument change to `resize`, sorry about that. I've pushed a set of fixes to git master.

**Comment by jcupitt** [comment]
... to explain the change, the `Interpolate` class is a 2D interpolator. These are still used for `affine`, `mapim` and others. 

Resize now uses a pair of fast orthogonal 1D resizing kernels, so there's a new thing to pick the kernel you want. The default is lanczos3, I'd just use that. 

You probably no longer need the final sharpening step you have in your code, it should look great without that. 

I'll wait a day or so for the gem to settle again, then push the updates. Thanks for pointing these problems out.

**Comment by ioquatix** [comment]
Thanks that looks good.
