### ISSUE TITLE
Function seems overly complex...

### ISSUE THREAD

**Issue by ioquatix** [jcupitt/ruby-vips#80]
https://github.com/jcupitt/ruby-vips/blob/9aae997817c13ba9dd71a2d28dfc62246654fa08/lib/vips/call.rb#L10-L214

Just wondering if this function is more complex than it needs to be. It looks like it's doing a lot of "redundant" processing. Could it be simplified?

Also, the function is hard to read and understand. I believe it's covering too much "surface area". Perhaps it could be broken up into smaller more manageable bits.

**Comment by ioquatix** [comment]
Also, this comment disturbs me slightly: https://github.com/jcupitt/ruby-vips/blob/9aae997817c13ba9dd71a2d28dfc62246654fa08/lib/vips/call.rb#L3-L7

**Comment by jcupitt** [comment]
Yes, it wasn't easy to get that working. See for example:

https://sourceforge.net/p/ruby-gnome2/mailman/message/34555202/

The crashes were if a Ruby GC hit during vips object construction. It seems stable now: I use ruby-vips on quite large projects. 

Yes, perhaps `call_base_nogc` should be broken into a class and a set of methods. I don't think there's much redundant processing, but I'm often wrong.

**Comment by ioquatix** [comment]
It's probably more a matter of style. The function is 200 LOC which is pretty big, and looks like it could do with a bit of refactoring.

As for the GC issue, it's a nasty hack and perhaps you should bring that discussion to ruby-dev mailing list for discussion.

**Comment by jcupitt** [comment]
The crashes are in gobject-introspection, so I think it'd be for them to fix, if anyone. 

I made them a sample crasher, but it was huge, unfortunately, and I'm not sure they ever investigated.  The way forward would probably be to make a smaller crash demo for them.

**Comment by jcupitt** [comment]
I've reworked it, it's probably a bit more straightforward.

**Comment by jcupitt** [comment]
This is in 1.0.3, I'll close.
