### ISSUE TITLE
Strange issue after running web server for several days

### ISSUE THREAD

**Issue by ioquatix** [jcupitt/ruby-vips#81]
```
Vips::Error: No such option 'autorotate',
/srv/http/files.geozone.io/vendor/bundle/ruby/2.3.0/gems/ruby-vips-1.0.2/lib/vips/call.rb:136:in `block in call_base_nogc'
/srv/http/files.geozone.io/vendor/bundle/ruby/2.3.0/gems/ruby-vips-1.0.2/lib/vips/call.rb:126:in `each'
/srv/http/files.geozone.io/vendor/bundle/ruby/2.3.0/gems/ruby-vips-1.0.2/lib/vips/call.rb:126:in `call_base_nogc'
/srv/http/files.geozone.io/vendor/bundle/ruby/2.3.0/gems/ruby-vips-1.0.2/lib/vips/call.rb:221:in `call_base'
/srv/http/files.geozone.io/vendor/bundle/ruby/2.3.0/gems/ruby-vips-1.0.2/lib/vips/image.rb:430:in `new_from_file'
/srv/http/files.geozone.io/lib/geozone/image_resizer.rb:12:in `input_image'
/srv/http/files.geozone.io/lib/geozone/image_resizer.rb:19:in `resize'
```

Restarting the web server fixed the issue.

Don't have time to look into it right now but may try to some time in the next month.

**Comment by jcupitt** [comment]
Hi, could it be low memory? Strange things can happen when memory gets low. 

ruby-vips 0.3 scheduled occasional GCs, but that code has gone from 1.0 since memory behaviour seems much better. You could try an explicit GC every 100 requests.

**Comment by ioquatix** [comment]
I have been running GC after each request. However today I did some more digging.

```
[4] pry(main)> Vips::Image.new_from_file("/tmp/RackMultipart20160722-16265-106mq0w.tif", autorotate: true)
Vips::Error: No such option 'autorotate',
from /srv/http/files.geozone.io/vendor/bundle/ruby/2.3.0/gems/ruby-vips-1.0.2/lib/vips/call.rb:136:in `block in call_base_nogc'
[5] pry(main)> Vips::Image.new_from_file("/tmp/test.jpg", autorotate: true)
=> #<Vips::Image:0x24e0c58 ptr=0x3ab9010>
```

It looks like the API is file format dependent?

So, if we have a TIF, the api doesn't provide an autorotate option?

**Comment by ioquatix** [comment]
However, I just checked several other instances of the problem and they relate to JPEGs.

**Comment by jcupitt** [comment]
Hi, tiff autorotate is a git master feature, it'll be in 8.4. 8.3 only has jpeg autorotate. 

Unfortunately the website docs are from git master, not current stable. I fixed a whole range of awful doc problems in the current dev cycle. I was getting quite a few issues on github caused by broken things in the docs, so I decided to overwrite the stable docs with the much better docs from master. 

It's very bad having future features (like tiff autorot) in there, but the docs are so much better I felt it was worth it. Hopefully when 8.4 is done in a few weeks this mess will disappear.

Sorry for the confusion.

**Comment by ioquatix** [comment]
@jcupitt The problem is not really due to documentation, but I appreciate your effort in this regard.

The problem is we are using `new_from_file` and we want it to autorotate if at all possible. Firstly, users shouldn't be providing `tiff` images but I guess that's happening in some cases by one of our developers by accident. When a `tiff` is supplied, the contact I expected of the API breaks. i.e.

`new_from_file(path, autorotate: true)`

Is this correct? Will it work? We don't know unless we somehow know that path is a jpg or tiff data.

This is fundamentally my problem. **The arguments to the function are not deterministic.**

Secondly, it seems like in some cases the API is breaking. I wonder if this relates to the `gobject-introspection` GC issue. I feel like what I'm seeing is some kind of internal corruption. So, there are two issues being here, one is easy to reproduce and the other is much harder.

This issue relates to the second one - over time the API seems to break for some reason - i.e. autorotate: true for JPEG images fails.

Here are some example errors I dug up:

```
request.params.file: {:filename=>"RackMultipart20160721-20938-1esc23t.jpg", :type=>"image/jpeg", :name=>"file", :tempfile=>#<Tempfile:/tmp/RackMultipart20160721-22694-eg0z4o.jpg>, :head=>"Content-Disposition: form-data; name=\"file\"; filename=\"RackMultipart20160721-20938-1esc23t.jpg\"\r\nContent-Type: image/jpeg\r\n"}
request.params.foreign_key: "28330"
request.params.group_key: "104035"

Vips::Error: No such option 'autorotate',
```

```
request.params.file: {:filename=>"RackMultipart20160721-20938-wznjf7.jpg", :type=>"image/jpeg", :name=>"file", :tempfile=>#<Tempfile:/tmp/RackMultipart20160721-22694-14y790a.jpg>, :head=>"Content-Disposition: form-data; name=\"file\"; filename=\"RackMultipart20160721-20938-wznjf7.jpg\"\r\nContent-Type: image/jpeg\r\n"}
request.params.foreign_key: "28331"
request.params.group_key: "104035"

Vips::Error: No such option 'autorotate',
```

It might be possible that even though the file has a jpg extension, it's actually a tif. We have 21,000+ images in our system, from many many external sources, and we've seen all sorts of crap (e.g. CMYK jpegs, TIFFs for print being used in web pages or being uploaded, etc).

**Comment by jcupitt** [comment]
Could you perhaps be reusing filenames, or using filenames without a type extension? I wonder if it could be a caching problem. 

You probably don't need a full GC on every request, I expect you know.

**Comment by ioquatix** [comment]
1/ I don't believe the file names are being reused. But, the caching system in vips concerns me a little bit. I'd rather implement a cache at a higher level unless it's fundamentally difficult to do that. From my perspective, I know more about my use case and how things should be cached than vips. We have one-off resize operations and don't want any caching really, or at most, perhaps per-request cache for the resize operations if that's actually helpful.

2/ Yes, we don't need full GC except that I've found the system is unpredictable in some cases without it. So, we amortise the GC into each request and it simplifies the API and the related memory retention issues we were having.

**Comment by ioquatix** [comment]
If this issue pops up again, the file in /tmp should be available. I'll capture it and if possible I'll report on its format... that way we know if it's because its a `file.jpg` which actually contains `tiff` data.

**Comment by jcupitt** [comment]
`.new_from_file()` is a meta-operation. It runs a sniffer to detect the filetype, then executes the operation that the sniffer recommended. So for jpeg files, it's exactly equivalent to `.jpegload(filename, options)`.

Although you can give loader-specific options to `.new_from_file()`, it can obviously fail if the loader vips ends up using does not support that feature. `vipsthhumbnail` has this problem: it has to detect filetype before using things like shrink-on-load. 

I think in this case the best fix would be to do the autorot yourself. Load the image without the option, then use `.autorot()` to get it upright. This should automatically start working with tiffs as well when 8.4 comes out.

http://www.vips.ecs.soton.ac.uk/supported/8.2/doc/html/libvips/libvips-conversion.html#vips-autorot

http://www.rubydoc.info/gems/ruby-vips/1.0.2/Vips/Image#autorot-instance_method

**Comment by jcupitt** [comment]
You can disable the cache with `Vips::cache_set_max(0)`, I expect you know.

Perhaps there should be an environment variable as well?

**Comment by jcupitt** [comment]
Oh, doing the autorot yourself should save a lot of time too. 

If you autorot during load, vips will need to rotate the whole image (obviously). If you rotate at the end of processing, you only need to rotate the reduced size image. 90 degree rotate is surprisingly expensive for large images since it triggers such a huge amount of memory traffic. 

Autorot during load also breaks sequential mode, so you'll lose the nice streaming behaviour, and you'll see a large spike in memory use.

`vipsthumbnail` does autorot right at the end, and does it via an explicit memory buffer so as not to mess up streaming:

https://github.com/jcupitt/libvips/blob/master/tools/vipsthumbnail.c#L571

It might be worth quickly looking over the vipsthumbnail code. How do you handle transparency, for example? Strictly, you should premultiply alpha before resizing:

https://github.com/jcupitt/libvips/blob/master/tools/vipsthumbnail.c#L430

It has some useful code for things like loading SVG at the correct resolution as well.

**Comment by ioquatix** [comment]
We take one image and resize it to 6+ other resolutions, so rotating as the first step is probably more efficient.

**Comment by ioquatix** [comment]
Haven't experienced this for ages so going to assume it's been fixed.

**Comment by jcupitt** [comment]
OK, good to hear.

**Comment by ioquatix** [comment]
Also, sorry to hijack the thread slightly, but I made https://github.com/ioquatix/vips-thumbnail because I really needed something like this. I might adapt it to use vips_thumbnail when that comes out.
