### ISSUE TITLE
resize function truncates size which is probably a bug

### ISSUE THREAD

**Issue by ioquatix** [jcupitt/ruby-vips#82]
For an image of size `[2000, 1333]`, scaling to size `[640,480]` - we first scale to `[720,480]` but there is a bug with the resize function which truncates the size to `[720,479]`.

```
[34] pry(main)> Rational(480, 1333).to_f
=> 0.3600900225056264
[35] pry(main)> 1333 * _
=> 479.99999999999994
```

I'm assuming it's because it truncates the above result to an integer rather than rounding it (which should be what it does, since a floating point scale factor is inherently inaccurate).

After calling image.resize(Rational(480, 1333))

```
image.width 720 image.height: 479
```

In theory, the Rational should preserve the intention of the scale operation, but this obviously is being converted to a float and truncated.

**Comment by ioquatix** [comment]
Probably something getting truncated here https://github.com/jcupitt/libvips/blob/master/libvips/resample/resize.c#L174-L178

**Comment by jcupitt** [comment]
vips always rounds down to try to avoid fractional pixels at image edges. 

`vipsthumbnail` handles this by adding a small amount to the target size before calculating the resize factor:

https://github.com/jcupitt/libvips/blob/master/tools/vipsthumbnail.c#L188

**Comment by jcupitt** [comment]
This has changed in 8.4: libvips now does round to nearest for image resize. I'll close.
