### ISSUE TITLE
Question: Set BandFormat for RAW images

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/ruby-vips#86]
(Finally up and running, thanks!)

I have a simple 512x512 8bpp RAW images I'm loading using:`Vips::Image.rawload(file, 512, 512, 1)` and that works fine.

However, I also have a 512x512 32bpp floating point RAW image.  Is there a way to specify this?

I tried `image.format = :double` but that leads to: `vips warning: tilecache: error reading tile, file has been truncated`

Thanks,
Simon

**Comment by jcupitt** [comment]
Yes, use `rawload` and set bands to 4, it'll give you a 512x512, four bytes per pixel image. Then use `copy` to change the image header so it's tagged as 1 band float.

The C docs have some notes on using `copy` like this:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#vips-copy

**Comment by harukizaemon** [comment]
Ahh, copy!  I'm an idiot.  Thank you!  Perfect.

**Comment by jcupitt** [comment]
Demo:

```
john@kiwi:~/pics$ vips black x.v 512 512
john@kiwi:~/pics$ vips linear x.v x2.v 1 128
john@kiwi:~/pics$ vipsheader x2.v
x2.v: 512x512 float, 1 band, b-w
john@kiwi:~/pics$ vips rawsave x2.v rawfloat
john@kiwi:~/pics$ ls -l rawfloat 
-rw-rw-r-- 1 john john 1048576 Sep  7 17:55 rawfloat
john@kiwi:~/pics$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):003:0> x = Vips::Image.rawload "rawfloat", 512, 512, 4
=> #<Vips::Image:0x2e50fe0 ptr=0x2e0e1a0>
irb(main):004:0> x = x.copy :bands => 1, :format => :float
=> #<Vips::Image:0x2b739a8 ptr=0x2e0e330>
irb(main):005:0> x.avg
=> 128.0
```

**Comment by harukizaemon** [comment]
Thanks.  So I tried that and, I suspect it's just late and I've had a long day because when I do so, it produces 100% white images.  I shall have another go tomorrow.

**Comment by jcupitt** [comment]
I guess you're outside the 0 - 255 range that JPG or PNG can produce. If you have a float image where every pixel is >255, you'll just see white when you save as png.

You can save as tiff. vips supports float tiff and the full range should be in there. Or you can apply some kind of scaling so it fits the range of 8 bit images. `#scale' will search an image and pick a scale and offset to fit the numeric range to 0-255.

**Comment by harukizaemon** [comment]
So, turns out it's actually a u32 greyscale image, not f32.  I'm getting these images as the output of some other process so it's tough working out how to process them - image processing isn't my forte as you may have gathered :)

**Comment by jcupitt** [comment]
Ah OK, you can `.copy(:format => :uint)` then, I guess you found.
