### ISSUE TITLE
extract_area silently fails

### ISSUE THREAD

**Issue by eltiare** [jcupitt/ruby-vips#87]
If you try to extract outside the dimensions of the image, both the function and writing the file appears to succeed but the file isn't actually created. I found this out thanks to a floating point error (#82), wherein the image was getting resized to height of 199 and I was expecting it to be 200.

Feel free to request an example. It's late and I wanted to get this in before I forgot tomorrow.

**Comment by eltiare** [comment]
To be clear: I expect the code to explode if I try to do something that doesn't make any sense like this. A helpful error message that I'm trying to extract out of bounds would be awesome.

**Comment by jcupitt** [comment]
Hi @eltiare, yes, that's what should happen, it'll raise an exception with an error message. Perhaps you have a catch somewhere that's masking it?

```
irb(main):009:0> x = Vips::Image.black 100, 100
=> #<Vips::Image:0x1418920 ptr=0x1a464d0>
irb(main):013:0> x.crop 10, 10, 100, 100
Vips::Error: extract_area: bad extract area

	from /home/john/packages/gems/gems/ruby-vips-1.0.3/lib/vips/call.rb:184:in `build'
	from /home/john/packages/gems/gems/ruby-vips-1.0.3/lib/vips/call.rb:249:in `invoke'
	from /home/john/packages/gems/gems/ruby-vips-1.0.3/lib/vips/call.rb:278:in `call_base'
	from /home/john/packages/gems/gems/ruby-vips-1.0.3/lib/vips/image.rb:395:in `method_missing'
	from (irb):13
	from /usr/bin/irb:11:in `<main>'
```

**Comment by eltiare** [comment]
Hm... maybe. I'm also using version 1.02 because I couldn't get 1.03 to compile on my system. Somebody else already posted a ticket for that one.

**Comment by eltiare** [comment]
I'm catching it for validations, but maybe CarrierWave doesn't report errors on what happens with the sub-versions of an uploader. That's probably it. I'll double-check and then close if that's the case.

**Comment by jcupitt** [comment]
Oh dear, 1.0.3 should have worked. The 1.0.3 ticket was a `PKG_CONFIG_PATH` that hadn't been set, or alternatively a `PATH` that didn't have `/usr/local/bin` at the front, depending on how you look at it.

**Comment by eltiare** [comment]
No worries. I'll give it all a shot by Monday.

**Comment by harukizaemon** [comment]
@eltiare The ticket @jcupitt is referring to is: https://github.com/jcupitt/ruby-vips/issues/84

**Comment by eltiare** [comment]
I was able to get 1.0.3 installed properly. I've not been able to confirm the error, though. I'll keep y'all updated.

**Comment by felixbuenemann** [comment]
@jcupitt I think this was fixed already. There used to be a problem in ruby-vips where it would return nil on error instead of raising an exception, but you fixed it. I don't remember if it was fixed in ruby-vips or libvips.

**Comment by jcupitt** [comment]
I don't remember either! Let's close. @eltiare could you reopen if there's still a problem?

**Comment by eltiare** [comment]
Absolutely. 👍

**Comment by jcupitt** [comment]
You are probably trying to extract an area outside the image.

If you're sure the area is inside, please open a new issue with a sample image and some code that reproduces the problem.
