### ISSUE TITLE
Question: Is it possible to specify vips-concurrency?

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/ruby-vips#88]
Specifically, I'm running `dzsave` in parallel with a few other not so CPU intensive non-image processing, and it's, understandably hogging the CPU :)

I tried  `image.dzsave(..., vips_concurrency: 1)` and received `Vips::Error: No such option 'vips_concurrency'`.

Is there a way to set it?

Thanks for the awesome software BTW!!!

**Comment by jcupitt** [comment]
It's supposed to be `Vips::set_concurrency 1`, but I see it's not actually available from Ruby, that header is not being scanned. I'll fix it.

Meanwhile, set the `VIPS_CONCURRENCY` environment variable, something like `ENV["VIPS_CONCURRENCY"] = "1"` before you require vips.

**Comment by harukizaemon** [comment]
Ahh! Thanks.  That makes sense.  I'll add the ENV variable as a work-around for now -- on my dev laptop my IDE becomes totally unusable :)

**Comment by jcupitt** [comment]
Yes, `dsave` really hammers the filesystem, it'll make 100,000 small files in just a minute or two.

The OS X filesystem is very, very slow and crappy (there's a new one coming soon, thank goodness) and it struggles. Have you tried zip output instead?

```
$ vips dzsave hugefile.tif x.zip
```

It'll directly write a large zipfile and won't use the filesystem (except for the zip itself), it might help. The zip is obviously much more convenient to upload to a server too, and takes up less space.

Some people modify the deepzoom viewer to work directly from the zipfile, which saves more time and space.

**Comment by harukizaemon** [comment]
This is actually backend processing of images i.e. already on the server.  Probably won't be so bad on the grunts boxes but there is loads of other stuff going on them too all happening via app controlled queues so would be good to be able to control the concurrency.

**Comment by jcupitt** [comment]
Ah OK. Yes, then set it to 1, I agree.

**Comment by jcupitt** [comment]
I've added `concurrency_set` to libvips master, it'll be in 8.4.

**Comment by harukizaemon** [comment]
Brilliant.  Thank you!

**Comment by harukizaemon** [comment]
Is there someway to get notified of new releases to libvips and vips-ruby?

**Comment by jcupitt** [comment]
I announce new libvips and nip2 versions on the vips mailing list. I think ruby-gems will notify you of new versions of gems, won't it?

**Comment by harukizaemon** [comment]
Looks like `concurrency_set` is no longer available in the latest release:

```
NoMethodError: undefined method `concurrency_set' for Vips:Module
```

Is there an alternative?

**Comment by jcupitt** [comment]
Hello again, you're right, it's missing, I'll put it back.

You can still use `ENV["VIPS_CONCURRENCY"] = "1"` before requiring vips.

**Comment by harukizaemon** [comment]
No big deal. I'm setting the environment variable anyway. Just upgrading some code and it barfed :)
