### ISSUE TITLE
Question: RAW image endian-ness

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/ruby-vips#90]
I have some RAW files from a piece of software that was run on PowerPC and everything is BigEndian. When loaded on an Intel box, everything appears to be treated as LittleEndian and comes out entirely black (and sometimes white).

Currently I'm doing this when loading the RAW images:

```
original = Vips::Image.rawload(file, width, height, bytes)
original = original.copy(bands: bands, format: format, interpretation: interpretation)
```

Is there a way I can also specify the endian-ness?

Thanks once again for your magnificent software!

**Comment by harukizaemon** [comment]
Damn! Just as I hit post, I find `flags: :bigendian` as a parameter to `rawload` bah!

I'll try that out

**Comment by jcupitt** [comment]
You need `.byteswap()`, add it as another line after your `.copy()`:

http://www.rubydoc.info/gems/ruby-vips/1.0.3/Vips/Image#byteswap-instance_method

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-conversion.html#vips-byteswap

I'll add a note to the docs for `rawload` pointing people at `byteswap`.
