### ISSUE TITLE
Question: Any way to read more than first page of a multi-page TIFF?

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/ruby-vips#91]
I have some 3D images represented as multipage TIFFs. I can't see anything in the meta/header data exposed through the library to indicate that a file has multiple pages, or for that matter to be able to read other than the first page. Is there currently a way to do so?

Thanks.

**Comment by jcupitt** [comment]
Hi, yes, you can use the `page` parameter. 

```
$ vips tiffload
load tiff from file
usage:
   tiffload filename out
where:
   filename     - Filename to load from, input gchararray
   out          - Output image, output VipsImage
optional arguments:
   flags        - Flags for this file, output VipsForeignFlags
   disc         - Open to disc, input gboolean
			default: true
   access       - Required access pattern for this file, input VipsAccess
			default: random
			allowed: random, sequential, sequential-unbuffered
   page         - Load this page from the image, input gint
			default: 0
			min: 0, max: 100000
   autorotate   - Rotate image using orientation tag, input gboolean
			default: false
```

In Ruby:

```
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.new_from_file "my_pyramid.tif"
=> #<Vips::Image:0x5558f4ee66a8 ptr=0x5558f4ead020>
irb(main):003:0> x.width
=> 9372
irb(main):004:0> x = Vips::Image.new_from_file "my_pyramid.tif", :page => 2
=> #<Vips::Image:0x5558f4fad848 ptr=0x5558f4ead1b0>
irb(main):005:0> x.width
=> 2343
```

**Comment by harukizaemon** [comment]
Ahh. Excellent! Is there a way to query how many pages there are?

FWIW, what I'm trying to do is extract all the pages into a single "toilet roll" RAW file.

**Comment by jcupitt** [comment]
Oh, you're right, there's no way to get "number of pages". The TIFF file format doesn't track this, all it lets you do is keep calling `NextDirectory()` until you see an error. 

In Ruby you'd need a little loop and something to catch exceptions.

**Comment by harukizaemon** [comment]
Right! I can probably go there. Thanks.

**Comment by jcupitt** [comment]
Haha, I like the "toilet roll" name. 

The pdfload operation as an option for this: you can set `n`, meaning load N pages starting at `page` as a toilet roll. This makes sense for PDF since pages are almost always the same size and so they fit together neatly. TIFFs are often a variety of sizes and they won't usually line up properly. 

You could just open repeatedly and append images with `join`, that should be fine for a few hundred pages. How large are the tiles you are working with?

You might need to experiment with access modes and the open threshold to keep memory use under control. It depends what kind of processing you need.

**Comment by harukizaemon** [comment]
These are typically 512x512x512 3D images. The trick - because it's a largely automated system - is to identify when there are multiple pages so yeah, I guess I'll need to open the TIFF, and read page by page, appending to the RAW file until I get an exception.

**Comment by jcupitt** [comment]
Ah OK, yes I work with 512 x 512 x 80 x 40 images (PET scans of volumes over time). I have a thing to assemble DICOM images into toilet rolls, then I use `Vips::Image.grid()` to lay them out in whatever way I need for processing.

I use vips format images for holding the toilet rolls, and a huge nip2 workspace to find organs in the volumes, fit various tracer models and produce a large set of graphs.

You might find loading all those tiff slices takes a lot of memory, you'd need to experiment. You can always assemble in a series of passes, as long as speed isn't too important.

**Comment by jcupitt** [comment]
Hi again, I've started adding toilet roll read to tiff load and I've reached the point where I need a test image. I don't suppose you have a smallish one you could share?

Branch here, fwiw:

https://github.com/jcupitt/libvips/tree/add-tiffload-n-pages

**Comment by harukizaemon** [comment]
Hi @jcupitt,

I'll get you an example ASAP. Thank you!

**Comment by jcupitt** [comment]
I found this, which looks like roughly the right thing:

http://downloads.openmicroscopy.org/images/OME-TIFF/2016-06/bioformats-artificial/multi-channel-z-series.ome.tif

**Comment by jcupitt** [comment]
It seems to work for that image. I'll try making `tiffsave` write a multi-page tiff.

Does anyone used tiled multi-page TIFFs? I added code for that case, though I've not been able to test it.

**Comment by harukizaemon** [comment]
Sorry for the delay. I'll try get you a sample today. The images I'm dealing with come out of a scanner. I don't *think* I'd ever need to write them but hey, who knows?! :)

**Comment by jcupitt** [comment]
OK, all merged to master, thanks for suggesting this!
