### ISSUE TITLE
Problem with Ubuntu installation

### ISSUE THREAD

**Issue by bilby91** [jcupitt/ruby-vips#92]
Hi,

I'm trying to use the gem in Ubuntu 16.04 and I'm not having luck. I always get the following message:

```
irb(main):002:0> Vips::Image
Unable to load Vips
  Check that the vips library has been installed and is
  on your library path.
  Check that the typelib `Vips-8.0.typelib` has been
  installed, and that it is on your GI_TYPELIB_PATH.
GLib::Error: Typelib file for namespace 'Vips' (any version) not found
```

I have tried installing from package (v8.2.2) and building from source (v8.4.2). In any of both cases I can't manage to find the `Vips-8.0.typelib` file.

```
root@90f3f863b951:/# find . -name "*.typelib"
./usr/lib/x86_64-linux-gnu/girepository-1.0/Gsf-1.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/GModule-2.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/Rsvg-2.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/cairo-1.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/fontconfig-2.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/PangoFT2-1.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/DBusGLib-1.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/PangoXft-1.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/GdkPixbuf-2.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/xrandr-1.3.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/libxml2-2.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/GLib-2.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/Pango-1.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/xlib-2.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/DBus-1.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/freetype2-2.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/Gio-2.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/xfixes-4.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/PangoCairo-1.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/GL-1.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/xft-2.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/GObject-2.0.typelib
./usr/lib/x86_64-linux-gnu/girepository-1.0/GIRepository-2.0.typelib
./usr/lib/girepository-1.0/Gtk-2.0.typelib
./usr/lib/girepository-1.0/GdkX11-2.0.typelib
./usr/lib/girepository-1.0/Atk-1.0.typelib
./usr/lib/girepository-1.0/Gdk-2.0.typelib
./usr/lib/girepository-1.0/SpiceClientGLib-2.0.typelib
```

**Comment by jcupitt** [comment]
Hi, Ubuntu 16.10 has the typelib in package called `gir1.2-vips-8.0`, I think I remember something like that on 16.04. If you start synaptic and type `vips` in the search bar, it should come up.

When building from source, you need  `gobject-introspection` installed for the typelib to be built. Check the summary at the end of the configure output, you should see something like:

```
gobject introspection: 			yes
```

**Comment by bilby91** [comment]
@jcupitt Thanks for the help!

The `gir1.2-vips-8.0` package works but I need to build it form source now. The `./configure` output show  `gobject introspection: no` but I have it installed. 

Anything im missing ?

**Comment by jcupitt** [comment]
Maybe you are missing the .pc file? Try:

```
$ pkg-config gobject-introspection-1.0 --modversion
1.50.0
```

libvips needs 1.30 or later.

**Comment by jcupitt** [comment]
Looks like that file is in `libgirepository1.0-dev`.

```
$ dpkg -S /usr/lib/x86_64-linux-gnu/pkgconfig/gobject-introspection-1.0.pc
libgirepository1.0-dev:amd64: /usr/lib/x86_64-linux-gnu/pkgconfig/gobject-introspection-1.0.pc
```

**Comment by tomasc** [comment]
@jcupitt I am running into same issue pre-installing libvips with ruby-vips on TravisCI – so that I could run tests of a lib that's using ruby-vips:

https://github.com/tomasc/dragonfly_libvips
https://travis-ci.org/tomasc/dragonfly_libvips/builds (tried a lot of things to make this work …)

Would you have a suggestion please? Thank you.

**Comment by tomasc** [comment]
@jcupitt, @bilby91 solved like this:

```
sudo apt-get update
sudo apt-get install -y gobject-introspection libgirepository1.0-dev
curl -O http://www.vips.ecs.soton.ac.uk/supported/8.4/vips-8.4.5.tar.gz
tar zvxf vips-8.4.5.tar.gz && cd vips-8.4.5 && ./configure && sudo make && sudo make install
export GI_TYPELIB_PATH=/usr/local/lib/girepository-1.0/
sudo ldconfig
```

**Comment by bilby91** [comment]
@tomasc I ended up building a custom Dockerfile for running the app. Let me know if need it I can send it to you.

**Comment by tomasc** [comment]
@bilby91 thank you, please do share the Dockerfile, thanks!

**Comment by bilby91** [comment]
@tomasc 

Here it is :). It builds from source ruby and vips

```
FROM ubuntu:14.04

MAINTAINER Martin Fernandez <fmartin91@gmail.com>

ENV HOME /root
ENV APP_HOME /var/www/app

ENV RUBY_MAJOR_VERSION 2.3
ENV RUBY_MINOR_VERSION 2.3.1
ENV GI_TYPELIB_PATH /usr/local/lib/girepository-1.0/

# Install dependencies
RUN apt-get update -qq && \
    apt-get install -y \
      wget \
      build-essential \
      openssl \
      libreadline6 \
      libreadline6-dev \
      curl \
      git-core \
      zlib1g \
      zlib1g-dev \
      libssl-dev \
      libyaml-dev \
      libsqlite3-dev \
      sqlite3 \
      autoconf \
      libc6-dev \
      ncurses-dev \
      automake \
      libtool \
      bison \
      nodejs \
      subversion \
      libpq-dev \
      libxml2-dev \
      libxslt1-dev \
      postgresql-client \
      pkg-config \
      glib-2.0 \
      libfftw3-dev \
      gettext \
      libgtk2.0-dev \
      python-dev \
      liblcms2-dev \
      libmagickwand-dev \
      libopenexr-dev \
      libcfitsio3-dev \
      gobject-introspection \
      libgirepository1.0-dev \
      flex \
      bison

# Build libvips
RUN curl http://www.vips.ecs.soton.ac.uk/supported/current/vips-8.4.2.tar.gz | tar xz; \
    cd vips-8.4.2; \
    dpkg --configure -a; \
    echo "/usr/local/lib/" >> /etc/ld.so.conf.d/local.conf; \
    ./configure; \
    make; \
    make install; \
    apt-get install -y libvips

# Build ruby
 RUN curl ftp://ftp.ruby-lang.org/pub/ruby/$RUBY_MAJOR_VERSION/ruby-$RUBY_MINOR_VERSION.tar.gz | tar xz; \
     cd ruby-$RUBY_MINOR_VERSION; \
     chmod +x configure; \
     ./configure --disable-install-rdoc; \
     make; \
     make install; \
     gem install bundler --no-ri --no-rdoc

# Set the working directory
WORKDIR $APP_HOME

# Add the Gemfile and Gemfile.lock into the image.
ADD Gemfile* $APP_HOME/

# Install ruby dependencies
RUN bundle install

# COPY app to container
COPY . $APP_HOME

# Expose puma port
EXPOSE 3000
```

**Comment by tomasc** [comment]
@bilby91 thanks – I ended up with similar solution – see my post above.

One slightly annoying thing is, that in order to use `ruby-vips` I have to make sure to have the `GI_TYPELIB_PATH` defined in all my apps. Is there any solution to this @jcupitt ?

**Comment by jcupitt** [comment]
You should only need to set the typelib path if you build your own libvips. If you use the bundled one, it should be fine without.

You could maybe just add `ENV['GI_TYPELIB_PATH'] = ENV['VIPSHOME'] + '/lib/girepository-1.0'` before require-ing vips. I've not tested it though.

**Comment by tomasc** [comment]
Thanks.
What do you mean by bundled one @jcupitt ?

**Comment by bilby91** [comment]
`apt-get install` one I believe

**Comment by tomasc** [comment]
I see – using `apt-get install` gave me only 7.x version, so unfortunately I always have to build from scratch.

**Comment by jcupitt** [comment]
Yes, the system one. Sorry, sounds like your Linux is a little too old. There was an API break for 8.0, but there shouldn't be another for many years, so hopefully this problem will go away eventually.

**Comment by tomasc** [comment]
Ok, no problem.

I am using pre-built [ruby 2.2.5](https://hub.docker.com/_/ruby/) Docker image as a base and I guess that comes with older Linux.

No problem rebuilding the libvips, the only bummer is having to remember setting the `GI_TYPELIB_PATH`. 

Is there a way that `ruby-vips` or `libvips` could use some default – for example as you pointed above?
