### ISSUE TITLE
get_value(Vips::META_LOADER) fails for gif files

### ISSUE THREAD

**Issue by raimondasv** [jcupitt/ruby-vips#93]
Might be the issue with `libvips`, still, reporting it here. We are using `Vips::META_LOADER` property to detect file types and correct Content-Type header. Unfortunately, it fails for gifs.

```ruby
require 'vips'

gif = Vips::Image.new_from_file('image.gif')
puts gif.get_value(Vips::META_LOADER)
```
produces
```
.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ruby-vips-1.0.3/lib/vips/image.rb:699:in `get_value': Field vips-loader not found. (Vips::Error)
	from gif.rb:4:in `<main>'
```
Gif loader is present in the system and Gif files can be loaded and manipulated. Just accessing `vips-loader` header value fails.

Same code for jpegs:
```ruby
require 'vips'

gif = Vips::Image.new_from_file('image.jpg')
puts gif.get_value(Vips::META_LOADER)
```
produces
```
jpegload
```

Maybe there are different means to detect image formats?

**Comment by jcupitt** [comment]
Hi, I agree, this looks like a libvips bug. I'll have a look.

**Comment by jcupitt** [comment]
OK, working for me now:

```
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.new_from_file "walk.gif"
=> #<Vips::Image:0x55bfd4bf3e90 ptr=0x55bfd4bb2010>
irb(main):003:0> x.get_value Vips::META_LOADER
=> "gifload"
```

Thank you for reporting this dumbness!

I'll try to think of a workaround for you in the meantime.

**Comment by raimondasv** [comment]
Amazing, @jcupitt thank you for doing this!

**Comment by jcupitt** [comment]
Looks like you can call `vips_foreign_find_load()` directly:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/VipsForeignSave.html#vips-foreign-find-load

```$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):009:0> Vips::Foreign.find_load("/home/john/pics/k2.jpg")
=> "VipsForeignLoadJpegFile"
irb(main):011:0> Vips::Foreign.find_load("/home/john/pics/walk.gif")
=> "VipsForeignLoadGifFile"
```

It gives you the canonical name of the loader class rather than the nickname, but it's obvious what it means. It should work on your libvips. There's `Vips::Foreign.find_load_buffer()` as well, which will sniff the image type from a string.

**Comment by raimondasv** [comment]
👍 

I've tried to avoid this because new_from_buffer would do detection again, no? However, the overhead seems to be small, so we are going to use `Vips::Foreign.find_load_buffer` for now and later update to and use `get_value(Vips::META_LOADER)`

**Comment by jcupitt** [comment]
Yes, it'll detect again, but detection is mostly quick. If you build your libvips without magick support and without support for things like openslide (very slow detection), it should be fast enough, I'd think.

**Comment by jcupitt** [comment]
I'll close, I think this is done.
