### ISSUE TITLE
DZI PNG compression

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/ruby-vips#95]
I ran an image through DZI using PNG as the output format and a compression factor of 9. However, when I take the resulting tiles and run them through `vips pngsave in.png out.png --compression=9` the resulting files are smaller. It's as if the Ruby version is ignoring the compression flag?

**Comment by harukizaemon** [comment]
For reference, I'm using the following to generate the DZI: `image.dzsave(slice_file, suffix: ".png", overlap: 1, tile_size: 511, depth: :onepixel, strip: true, compression: 9)`

**Comment by jcupitt** [comment]
Hi, you need to put the compression setting into the suffix. For example:

```
john@kiwi:~/pics$ vips dzsave k2.jpg x --suffix .png[compression=9]
john@kiwi:~/pics$ ls -l x_files/10/0_0.png 
-rw-r--r-- 1 john john 87927 Jan 25 13:40 x_files/10/0_0.png
john@kiwi:~/pics$ vips copy x_files/10/0_0.png x.png[compression=9]
john@kiwi:~/pics$ ls -l x.png 
-rw-r--r-- 1 john john 87927 Jan 25 13:41 x.png
```

**Comment by harukizaemon** [comment]
Interesting. The `--compression=9` works on the command line but when using Ruby I need to use `suffix: ".png[compression=9]`

Worked a treat. Thank you!

**Comment by jcupitt** [comment]
The `--compression` arg to `dzsave` sets the compression of the zip container,  not the PNG file. I see:

```
john@kiwi:~/pics$ vips dzsave k2.jpg x --suffix .png --compression=9
john@kiwi:~/pics$ ls -l x_files/10/0_0.png 
-rw-r--r-- 1 john john 88455 Jan 25 16:33 x_files/10/0_0.png
john@kiwi:~/pics$ vips copy x_files/10/0_0.png x.png[compression=9]
john@kiwi:~/pics$ ls -l x.png 
-rw-r--r-- 1 john john 87927 Jan 25 16:34 x.png
```

So the PNGs are saved with the default level 6 compression. You see the effect of `--compression` with zip output:

```
john@kiwi:~/pics$ vips dzsave k2.jpg x.zip --suffix .png
john@kiwi:~/pics$ ls -l x.zip
-rw-r--r-- 1 john john 4639363 Jan 25 16:35 x.zip
john@kiwi:~/pics$ vips dzsave k2.jpg x.zip --suffix .png --compression=9
john@kiwi:~/pics$ ls -l x.zip
-rw-r--r-- 1 john john 4639212 Jan 25 16:36 x.zip
```

Not very useful in this case.
