### ISSUE TITLE
Suspected bug with Image::scale

### ISSUE THREAD

**Issue by harukizaemon** [jcupitt/ruby-vips#99]
I tried using `Image::scale` and rather than scaling and returning an 8-bit image, it returns `1.0`:

```
image.min
# ==> 4000.4248046875

image.max
# ==> 25511.68359375

image.scale
# ==> 1.0

# Just in case
image.scale()
# ==> 1.0

image.min
# ==> 4000.4248046875

image.max
# 25511.68359375
```

**Comment by jcupitt** [comment]
Oh you're right, there's a name clash. There's a vips operator called `scale`, which rescales an image to fit 0 - 255, and there's a bit of metadata which records the scale of a convolution mask.

You can call the vips operator like this:

```
y = Vips::Image.scale x
```

I'll add a note to the docs.

**Comment by harukizaemon** [comment]
Awesome. Worked a treat. Thank-you.

**Comment by jcupitt** [comment]
OK, I added `scaleimage`, just scale renamed to avoid the name clash.

**Comment by harukizaemon** [comment]
Ahh nice. I was going to ask if it were possible to remap
It as eg `rescale`. Thanks!
